### PR TITLE
feat(widget): add a new rating range

### PR DESCRIPTION
**Pull request by mthuret**
ratings range

### CODE REVIEW

**Comment by bobylito** [comment]
Looks good to me. I'm not sure about the naming and that it is related to range (not a big deal though)

**Comment by mthuret** [comment]
About the naming `RangeRatings`:
Currently without default theming, this widget only provides span as stars. Also, I was thinking that maybe for a rating, a user will want to use some other icons than stars. (maybe heart, or whatever :))

Also, be aware that there is a wierd behavior that you can see with the e-commerce example : if you clear all filters or click again on a selected rating, the largest one would become the new selected one. That's because I use the Range connector which when no refinement is set, put its value to the largest range possible. 
To avoid that we can compute an extra props that will say if there's refinements or not. Do you have any other ideas ?

**Comment by mthuret** [comment]
And to complete my previous comment: we had a discussion with @vvo on how to implement this widget. At first, I used the NumericRefinementList. But this widget needs a static list of ranges. So it would have required some changes on the connector side, to handle both statics and dynamics range computation. (There's also this issue about the naming of NumericRefinementList #1306)

But considering the new issue with default values for Range, maybe it would have been better to modify NumericRefinementList. Anyway, need your thoughts about that guys :)

**Comment by vvo** [comment]
> (maybe heart, or whatever :))

good idea! :heart:

**Comment by vvo** [comment]
> Also, be aware that there is a wierd behavior that you can see with the e-commerce example : if you clear all filters or click again on a selected rating, the largest one would become the new selected one. That's because I use the Range connector which when no refinement is set, put its value to the largest range possible. 
> To avoid that we can compute an extra props that will say if there's refinements or not. Do you have any other ideas ?

The fact that the largest range is shown selected when there's no range selected is something we should do. Because it does represent the current search state. The user is free to handle this largest range as he wants, maybe with a "Clear" button or "All".

**Comment by bobylito** [comment]
I must say that I'm not sure I grasp the wholeness of the problem, so bear with me. I feel that if we need to work around a behaviour implemented as a connector using a new variable that will used only in one widget, we need a new connector.

In any case, the extension of a connector should be consistent with its role. If it's the case that's fine with me. Do you have an example of the API that you want to implement?

PS : http://explosm.net/comics/3902/

**Comment by vvo** [comment]
> I must say that I'm not sure I grasp the wholeness of the problem

I will sum it up: the current StarRating widget @mthuret implemented has a different behavior than what's available in IS V1.

In the instant_search dataset, ratings are ranged from 1 (min) to 5 (max). When the page loads, like https://community.algolia.com/instantsearch.js/examples/media/. The starRating widget is instantiated and no ratings refinement are selected. BUT it's lying, there's a default refinement being shown, which is "no refinement on ratings" => show all movies from 1 to 5.

So if you click on ★☆☆☆☆ & up then there's no effect on the result set. This is not good since a button should have some effect in this situation.

On amazon.com for example, ratings are ranged from 0 to 5, but they never show ☆☆☆☆☆ & up; because that's what's already being shown by default.

While in react-instantsearch, now the behavior when the page loads or when you deselect ★★★☆☆ is that ★☆☆☆☆ will be selected. Which is coherent with the search state but may be misleading.

So what we could do is always hide the largest range if not relevant (= already what's being shown), or gray it (as we want).

For now, let's do the obvious and let show the default range as being selected (☆☆☆☆★). Then we will iterate quickly once we decide that maybe, like on amazon.com, the largest range, if already applied, should not be shown. That's a design decision.

**Comment by vvo** [comment]
Also, one thing we are not doing good in IS V1 is that we do have movies that have five stars, but we are unable to refine only on them.

I would add this: if the Algolia stats reveals that there are some objects reaching the maximum rating, then show the refinement for ★★★★★ because it's useful for users.

And we can go even further, by denoting the available/unavailable ranges like how it's done today:

2016-09-21-154338_244x136_scrot

**Comment by mthuret** [comment]
Alright I make the following change : 

- largest range is by default always selected 
- display a line for the [max:max] range

**Comment by vvo** [comment]
Are we good here @mthuret? Do we also only display relevant ranges, or are we able to distinguish non relevant ranges via a specific theme prop?

**Comment by mthuret** [comment]
@vvo If you don't specify a min/max you got a rating line from lowerBound to upperBound. 
However if the count for a line is 0, I currently didn't add a specific classname for it. Do you want this to be added ?

**Comment by vvo** [comment]
> However if the count for a line is 0, I currently didn't add a specific classname for it. Do you want this to be added ?

I would say yes, since the current starRating widget has this ability (see https://github.com/algolia/instantsearch.js/pull/1317#issuecomment-248616488), and it is very valuable. If the range is not relevant then we should hint the display/user.

What do you think

**Comment by mthuret** [comment]
Yes that makes sens 👍

**Comment by mthuret** [comment]
Classnames were added. 

capture d ecran 2016-09-22 a 12 09 15

**Pull request merged**
