### PR TITLE
chore: add codesandbox ci

### PR DESCRIPTION
**Pull request by eunjae-lee**
**Summary**

This PR configures CodeSandbox CI app.

related to https://github.com/algolia/react-instantsearch/pull/2927

### CODE REVIEW

**Comment by eunjae-lee** [comment]
IIUC, it just replaces the dependency with the temporary one. I don't think they use it from script tag according to the sandbox created in the react-IS repo: https://codesandbox.io/s/eloquent-bush-wy34l

**Comment by francoischalifour** [comment]
What @Haroenv means is that [the template uses a script tag](https://github.com/algolia/create-instantsearch-app/blob/a2c0687d16fbb659307e99facccd12fad19f0301/instantsearch.js/index.html#L48) which CodeSandbox might not be able to replace during deployment.

**Comment by eunjae-lee** [comment]
Oops. Closed by mistake.

**Comment by eunjae-lee** [comment]
> What @Haroenv means is that [the template uses a script tag](https://github.com/algolia/create-instantsearch-app/blob/a2c0687d16fbb659307e99facccd12fad19f0301/instantsearch.js/index.html#L48) which CodeSandbox might not be able to replace during deployment.

You're right. What do you think of adding instantsearch.js as a dependency in create-react-app template and `import` it there? Any blocker? If not, I'll send a PR.

**Comment by Haroenv** [comment]
I think it's better to use a different example which imports

**Comment by francoischalifour** [comment]
Yeah I think it's a bit too early to move to imports in the sandbox because we document the UMD usage everywhere in the documentation. We can create an InstantSearch.js ESM template.

**Comment by eunjae-lee** [comment]
Okay sounds good. I guess I can just create a code sandbox which imports es module and use it as the base for the PRs.
Or, do you want to have it in a proper repo like doc-code-samples?

**Comment by francoischalifour** [comment]
That's fine to me!

**Pull request merged**
