### PR TITLE
Update algolia logos

### PR DESCRIPTION
**Pull request by LukyVj**

### CODE REVIEW

**Comment by LukyVj** [comment]
ping @vvo

**Comment by pixelastic** [comment]
Could you add a few screenshots of how it looks like on the website for future PR like this? Makes changes in design much easier to understand.

**Comment by vvo** [comment]
Good point, I am also close to have automatic PR deployed (for RIS)

**Comment by LukyVj** [comment]
Oh yeah my bad. Here is what I updated  :

**Pull request merged**
