### PR TITLE
chore: pin Yarn and Node versions

### PR DESCRIPTION
**Pull request by francoischalifour**
This is the equivalent of #3228 for the branch `feat/3.0`.

### CODE REVIEW

**Comment by Haroenv** [comment]
how come this can't be done my merging master into feat/3.0?

**Comment by francoischalifour** [comment]
I was wondering at what point we want to separate the two branches. Is it too early?

I'm especially thinking about the commit 6006fe1c59992f8cb7bf2dd09e004d9999e6e4c2 which is going to be annoying to merge with #3190.

**Comment by Haroenv** [comment]
It's the same for me, but with Vue InstantSearch I'm seeing annoyances now with having two completely separate branches

**Comment by francoischalifour** [comment]
Makes sense. I will try to resolve conflicts from `develop` and treat this PR accordingly.

**Comment by francoischalifour** [comment]
Handled in df23db14e397f0266709b9aa3b0f26d08501a0fd.

**Pull request closed without merging**
