### PR TITLE
chore: release v4.2.0

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Release Summary
- Version change: `v4.1.1` → `v4.2.0`
- Merge: `releases/v4.2.0` → `master`
- [Compare the changes between the versions](https://github.com/algolia/instantsearch.js/compare/v4.1.1...releases/v4.2.0)
> :warning: When merging this pull request, you need to **_"Squash and merge"_** and make sure the title starts with `chore: release v4.2.0`.
> After that, a commit `chore: release v4.2.0` will be added and `shipjs trigger` will be able to trigger the release based on the commit.
> Fore more information, please refer to the mergeStrategy section of the [guide](https://github.com/algolia/shipjs/blob/master/GUIDE.md#mergestrategy).
> Squash and merge

---
This is going to be published by the following command:
```
yarn publish --no-git-tag-version --non-interactive --tag latest
```
---
_This pull request is automatically generated by [Ship.js](https://github.com/algolia/shipjs)_

### CODE REVIEW

**Comment by francoischalifour** [comment]
Just checking – this is meant for trying the Ship.js configuration and not to be merged/released, right?

**Comment by eunjae-lee** [comment]
@francoischalifour correct. It's safe to merge/release but I created this to show the team how it's done. A slack message coming soon.

**Comment by tkrugg** [comment]
@eunjae-lee for a release it seems to me you wouldn't want to squash the commits, to preserve the history of the the feat, fixes, etc with their related PRs. So you'd want to just produce a merge commit. Did I misunderstand what meant?

**Comment by Haroenv** [comment]
@tkrugg, this isn't all the commits of the PR, this is the "version release" commit only

**Comment by eunjae-lee** [comment]
@tkrugg Haroen is correct.
When we used to have `develop` and `master`,
we had to make a merge commit to merge develop into master.

Now that we have only `master`, this PR is just creating a new commit on top of that which contains only version change, and change updates, etc.

**Comment by tkrugg** [comment]
Oh that makes sense, thanks!

**Comment by eunjae-lee** [comment]
Closing pr, because it was just for a demonstration.

**Pull request closed without merging**
