### PR TITLE
fix(poweredBy): Let users define their own poweredBy template

### PR DESCRIPTION
**Pull request by pixelastic**
Fixes: #1047

You can now pass an object to `poweredBy` in the `searchBox` widget like this:

```javascript
poweredBy: {
  template: 'Link to {{data.url}}', // Also accepts function
  cssClasses: {
    root: 'applied to wrapper',
    link: 'applied to link'
  }
}
```

Everything is handled directly in the widget, without the need for
a React component. This was overkill because we never update the
render of the `poweredBy` so it was easier to just generate the
template at init time without going through all the process of
creating a template.

I've also added more thorough tests. Users will be able to
independently change CSS classes or template.

### CODE REVIEW

**Comment by pixelastic** [comment]
I've used `poweredBy.template`. I wonder if `poweredBy.templates.item` is better?

**Comment by Jerskouille** [comment]
Wow, a PR so fast? :100: 
About the way you defined it, I'm just wondering: wouldn't this be the first time we wrap a template inside a subobject of a widget?

I couldn't find any other case of this, correct me if I'm wrong, but for consistency, it might be better to go with `templates.poweredBy`, and then `cssClasses.poweredBy{Root,Link}` or `cssClasses.poweredBy.{root,link}`, no?

**Comment by pixelastic** [comment]
We did it for the `showMore.templates` as well. And here we even had several templates (`active` / `inactive`).

I remember discussing it with @vvo at some point, and we more or less agreed that using a subobject was better, but we never wrote any standard for that. I'm open for discussing it

**Comment by Jerskouille** [comment]
I have no issues with it, if we're already using this elsewhere, I'm happy with these options. I'm just an advocate of consistency. :)

**Comment by vvo** [comment]
LGTM, even the template part is ok, no need for "item" here

**Pull request merged**
