### PR TITLE
docs: add jsx tags to InstantSearch

### PR DESCRIPTION
**Pull request by mthuret**

### CODE REVIEW

**Comment by mthuret** [comment]
Also inside the widget.pug layout we have this:

```
    p List of props exposed by the
      code=name
      |  widget
```

This is also used by the <InstantSearch> component. Do we want to add some logic here to make the distinction? 

see: https://community.algolia.com/instantsearch.js/react/widgets/InstantSearch.html

**Comment by vvo** [comment]
> p List of props exposed by the
>       code=name
>       |  widget

Yes and also in the left navigation, that would be kind of awesome :)

**Comment by vvo** [comment]
@mthuret Sorry I was not precise, do you think we could put `<SearchBox>` instead of `SearchBox` and other widgets, in the left nav also?

Maybe by just checking the category (connector or widget), we can add this easily?

**Comment by vvo** [comment]
Merging this one first then will see

**Pull request merged**
