### PR TITLE
chore(shrinkwrap): use uber/shrinkwrap

### PR DESCRIPTION
**Pull request by vvo**
PROS:
- consistent shrinkwrap, removes "from" weird things
- we should now be able to have a lot less noise when updating/adding
modules

CONS:
- need to be installed globally (weird stuff happens otherwise)
- not compatible with npm@3

This is currently my best solution to the shrinkwrap madness.

I updated the contributing guide, a lot easier now and faster to add,
update, remove packages.

I hope npm@3 gets better at shrinkwrap some day.

Also:
- removed a bunch of packages we did not use anymore
- updated some packages
- updated our linting rules with more defaults for react

### CODE REVIEW

**Comment by redox** [comment]
> need to be installed globally (weird stuff happens otherwise)

to run `npm shrinkwrap` or also to run `npm install` and contribute without adding news dependencies?

**Comment by vvo** [comment]
> to run npm shrinkwrap or also to run npm install and contribute without adding news dependencies?

Just to add/remove dependencies. I asked them if we could solve this

**Comment by redox** [comment]
LGTM :+1:

**Comment by vvo** [comment]
Will only try again on Monday to have local npm-shrinkwrap, they said it was feasible (https://github.com/uber/npm-shrinkwrap/issues/88#issuecomment-150640076)

**Comment by vvo** [comment]
ok managed to have it locally without any issue

**Comment by vvo** [comment]
+ updated to latest expect-jsx which handle key and refs. Fixed some linting.

**Comment by vvo** [comment]
Still some eslint fixes to do

**Pull request merged**
