### PR TITLE
docs(readme): list supported browsers

### PR DESCRIPTION
**Pull request by Haroenv**
**Summary**

@jonasba tested, and IE9 and lower does not work. Older Safari, Chrome, FF versions are not checked explicitly

**Result**

add a sentence to show we support the latest two versions

### CODE REVIEW

**Comment by Haroenv** [comment]
@oliviertassinari we have the misfiring images here too, but that's easy to manually view as a "pass"

**Comment by oliviertassinari** [comment]
I can submit a PR to hide the images in the CI, waiting for fixing the root issue.

**Comment by bobylito** [comment]
Thanks @oliviertassinari it's ok. That's just one more bug report for you :). Thanks for your help :)

**Comment by oliviertassinari** [comment]
Great, I will do that.

**Pull request merged**
