### PR TITLE
docs(hierarchical): Fix `cssClasses.depth` documentation

### LINKED ISSUE #1025: [Documentation] hierarchicalMenu `cssClasses.depth` option seems wrong
capture d ecran 2016-05-22 a 22 43 02

Probably a bad copy/paste. There's no "depth" element, but a class to differentiate the different depths of items in the hierarchy, right?

Proposition:
> CSS class to add to each item element to denote its depth. The actual level will be appended to the given class name (ie. if `"depth"` is given, the widget will add `"depth0"`, `"depth1"`, ... according to the level of each item).

### PR DESCRIPTION
**Pull request by pixelastic**
Fixes #1025

Gives more information on how the class is operating

image

### CODE REVIEW

**Comment by bobylito** [comment]
@vvo isn't the widget jsdoc/markdown generation done when we publish the page?

**Comment by pixelastic** [comment]
...

I clicked the "update branch" button and it created a merge commit...

I'll wait for @vvo answer and rebase everything

**Comment by vvo** [comment]
jsdoc is done when running npm run release but not automatically by travis when merged etc (because it would require travis commit).

@pixelastic yes the update button does merges, no big deal we can merge

**Comment by vvo** [comment]
Next time, you can submit all documentation quick fixes to master with "hotfix" in the commit body

**Comment by pixelastic** [comment]
Ok, I'll submit to master next time.

If I understand correctly, I still need to generate the HTML version when I submit to master because no `release` will be made, right?

**Comment by vvo** [comment]
Yes that's it

**Pull request merged**
