### PR TITLE
Fix the connector-docs link + typo

### PR DESCRIPTION
**Pull request by Meschreiber**
Previously the link for more info on connectors led to a 404.

### CODE REVIEW

**Comment by Haroenv** [comment]
Same here, shouldn't we make the absolute links work with a `<base>` tag maybe?

**Comment by bobylito** [comment]
Relative links work just fine.

**Comment by Haroenv** [comment]
This should also be a relative link then 🤔

**Comment by Meschreiber** [comment]
The relative link was going to https://community.algolia.com/instantsearch.js/connectors.html maybe because it was written as (../connectors.html)

**Comment by Meschreiber** [comment]
PS. Will follow branch naming conventions from now, sorry!

**Comment by Haroenv** [comment]
@Meschreiber, was fixed in another PR, thanks a lot, branch naming doesn't matter much for a patch 😄

**Comment by bobylito** [comment]
Yes indeed branch naming is not enforced. Thanks for contributing that is the most important ❤️

**Pull request merged**
