### PR TITLE
feat: Switch/Toggle widget

### PR DESCRIPTION
**Pull request by pixelastic**
Here is the switch/toggle widget that adds a boolean conjunctive filter and removes it with a checkbox.

Use case is hiding/showing all results that have for example `free_shipping: true`. When checked, only items with this attribute `true` will be displayed. When unchecked, all items will be displayed.

I renamed it from `switch` to `toggle` because naming variables `switch` in JavaScript caused issues as this is a reserved keyword.

Comments welcome

### CODE REVIEW

**Comment by pixelastic** [comment]
Oh, and as the instant search demo does not have any boolean attributes, there is no way to test it here. I tested on a custom index on my side.

**Comment by redox** [comment]
> Oh, and as the instant search demo does not have any boolean attributes, there is no way to test it here. I tested on a custom index on my side.

We'll add a randomly generated "free_shipping" attribute then.

**Comment by vvo** [comment]
@pixelastic The proposed API in #41 had `template` and `cssClass` in it, what about them? Do you implement them also?

About `template`: we could maybe have a default template, use it if no provided template. Otherwise use the provided template (like for multipleChoiceList).

> Oh, and as the instant search demo does not have any boolean attributes, there is no way to test it here. I tested on a custom index on my side.

It did have something like a switch at some point when we did the API proposal, in #41 there's a screenshot but now it's no more on the demo. Yes for adding it to the data.

**Comment by pixelastic** [comment]
@vvo: No I did not implemented the `template` and `cssClass` because once again we're going back to the same questions :)

I listen to the `checkbox` change event, so allowing for a custom template would raise again all the questions of how we will be able to correctly bind our event if we don't know what the template will compile too.

Regarding the `cssClass`, I'm not even sure the `label` wrapping the `checkbox` will be the final default template. Also, we won't even use this widget in the instant search, so I think we can just keep it like it is for now.

**Comment by vvo** [comment]
> Regarding the cssClass, I'm not even sure the label wrapping the checkbox will be the final default template. Also, we won't even use this widget in the instant search, so I think we can just keep it like it is for now.

100% agree to review the PR as it now because it's sufficient.




> I listen to the checkbox change event, so allowing for a custom template would raise again all the questions of how we will be able to correctly bind our event if we don't know what the template will compile too.

For this issue I thought we did solve it in the refinementList where you can have either a checkbox or  a link and we only listen for the item click event (and it bubbles from the checkbox or the link to the item element).

BUT no need to make anymore modifications on this one, just wanted your input on the onClick/template

**Comment by pixelastic** [comment]
The code we have on the refinementList for catching the event is quite complex IMHO, and we only needed it because we provided the user the ability to add a custom template. As I'm not doing it here, just listening to the checkbox change event is enough.

The thing is, the way we will handle event is tightly linked to if and how we handle the templates. If we do not let the user change the template and provide our own HTML markup, then we can listen to specific event on our own markup (like the change event on the `checkbox`).

If we let the user completely change the template, then it may or may not use a checkbox (which will in that case become only a design element and not part of the widget behavior). In that case, we'll have to listen to our events higher in the hierarchy (`click` event on the wrapper instead of `change` event on the checkbox). And as we've seen, this comes with its own strange bugs (`click` event firing twice when wrapping checkbox in label).

So, to conclude, I think putting the onclick on top would be the way to go if we go the template route. But as we're still ensure how to handle template, I'll just put that on hold for now :)

**Comment by pixelastic** [comment]
Ok, so I actually did the complete opposite of what I just said above :)

For adding the widget to the page example, I needed a template, so I added the option. I used `debounce` with `leading: true, trailing: false` though. It seems more straightforward to me than handling the specifics tagname cases, but I'm open to improvements.

I did not add the `cssClass`/`rootClass` property though, as this can be achieve either by editing the wrapping HTML or the `template.

**Comment by pixelastic** [comment]
I've added a bit of documentation (both code and human-readable) with a print screen. Ready to be merged after that.

**Comment by vvo** [comment]
I like the screenshot thing, we should do it for other widgets after.

**Comment by pixelastic** [comment]
@redox @vvo @bobylito: Comments? Otherwise ready to be merged.

**Comment by vvo** [comment]
Will merge soon

**Comment by vvo** [comment]
> Interesting trick! Have you tested on multiple browsers?

I think we did not test any other than chrome for now!

**Pull request merged**
