### PR TITLE
chore(issues): Update issue templates

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by bobylito** [comment]
I'm not it won't collide with the previous template 🤔

**Comment by Haroenv** [comment]
Why is the previous template not removed? 

Maybe this can be tried out in a test repo so we see how it behaves?

**Comment by bobylito** [comment]
Or we can try and fix it :)

**Comment by bobylito** [comment]
I will remove the old template :) @Haroenv No need for it actually

**Comment by bobylito** [comment]
@Haroenv Is there anything else I should do?

**Pull request merged**
