### PR TITLE
hotfix(home): adds spring back for stars + removes useless renderings

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by Shipow** [comment]
image

**Comment by bobylito** [comment]
@vvo how can I do an hot fix?

**Comment by vvo** [comment]
Yep so we merge into master, then you run:

```sh
VERSION=1.0.0 npm run gh-pages
```

**Comment by vvo** [comment]
Even after publishing gh-pages, it can take 10 minutes for the cloudflare cache to be purged

**Comment by vvo** [comment]
ah yes and then you can merge back master into develop.

also the commit message would have been "docs(stars): ..". Everything that is docs must be tagged "docs()". Even if hotfix, fix in docs etc..

You can still say "hotfix" in the body that's a good one

**Pull request merged**
