### PR TITLE
fix(starRating): Retrieve the correct count and use numericRefinement

### LINKED ISSUE #615: starRating disappearing once clicked in live docs
star-rating

### PR DESCRIPTION
**Pull request by Jerskouille**
Closes #615 .

### CODE REVIEW

**Comment by Jerskouille** [comment]
@redox Any thought on using a numeric disjunctive refinement instead of ORing integers ?

**Comment by vvo** [comment]
Ill let @redox have a look

**Comment by vvo** [comment]
@Jerskouille Do we still need to do this?

**Comment by Jerskouille** [comment]
I think so, I'll check.

**Comment by vvo** [comment]
Because #615 was fixed by adding the right dataset, I just want to be sure on what we are fixing here if you can ellaborate.

**Comment by Jerskouille** [comment]
The fact that the count were not calculated with the sum of the previous ones. (3 &Up was using `facet_values[note].data[3]` instead of `facet_values[note].data[3,4,5]`)
The numericRefinement instead of ORing might not be needed anymore.

**Comment by Jerskouille** [comment]
cap
`2&Up`'s count is lower than `3&Up`'s.

**Comment by Jerskouille** [comment]
I'll remove the `numericRefinement` part of the PR.

**Comment by Jerskouille** [comment]
@redox Could you confirm it's the behaviour you wanted?

**Comment by redox** [comment]
:+1: @Jerskouille

**Comment by vvo** [comment]
coool

**Pull request merged**
