### PR TITLE
feat(widget): rename rangeRatings to starRatings + design improvements

### PR DESCRIPTION
**Pull request by mthuret**
image

### CODE REVIEW

**Comment by vvo** [comment]
Small change: it should be StarRating I believe, not StarRatings? see https://www.google.com/search?q=react+star+%22ratings%22

**Comment by vvo** [comment]
Also https://github.com/cameronroe/react-star-rating

**Comment by vvo** [comment]
cc @dzello Can you help naming the widget shown in the description:

- `<StarRating/>`
- `<StarRatings/>`
- ?

**Comment by mthuret** [comment]
I put an `s` because it's a list of ratings (and not only a single line of stars).
But I'm fine with starRating if everybody agree :)

**Comment by vvo** [comment]
> I put an s because it's a list of ratings (and not only a single line of stars).

Yes same, I just want to ensure we are not just doing bad english here :8ball:

**Comment by mthuret** [comment]
Sure 👍 :)

**Comment by dzello** [comment]
I think the singular version works best. There are multiple star ratings but we are filtering by the (singular) star rating of the record. Also as a umbrella term for the concept of rating by stars, the singular form works better. This is my best attempt to explain, I hope it makes sense!

**Comment by vvo** [comment]
Let's go for StarRating @mthuret

**Comment by mthuret** [comment]
done :)

**Pull request merged**
