### PR TITLE
Fix Toggle component used with CurrentRefinements

### PR DESCRIPTION
**Pull request by klacointe**
Steps to reproduce:

1.  Use Toggle with CurrentRefinements
2.  Click on Toggle component
3.  Refinement is shown in CurrentRefinements
4.  Remove Refinement from CurrentRefinements
5.  BUG: Toggle was not unchecked.

### CODE REVIEW

**Comment by klacointe** [comment]
Workaround before this get merged:

```
import Toggle from 'react-instantsearch/src/components/Toggle'
import { connectToggle } from 'react-instantsearch/connectors'

const FixedToggle = (props) => {
  return (
    <Toggle                                                                        
      {...props}
      currentRefinement={props.checked}
    />
  ) 
}

const ConnectedFixedToggle = connectToggle(FixedToggle)
```

Then use `ConnectedFixedToggle` instead of `Toggle`.

**Comment by mthuret** [comment]
Hi @klacointe, thank you very much for reporting this! 

I think the appropriate fix would be to rename the prop `checked` to `currentRefinement` inside the `connectToggle` connector. That way we stay consistent with all the other connectors. 

I can make the fix if you want, or you can modify your PR. Tell me what works best for you :)

**Comment by klacointe** [comment]
Hi @mthuret, thanks for you reply.

I've updated the PR.

**Comment by klacointe** [comment]
Thanks @mthuret !

**Pull request merged**
