### PR TITLE
chore(ts-migration): renames breadcrumb files

### PR DESCRIPTION
**Pull request by nunomaduro**
As usual, this is the first pull request while migrating breadcrumb files. This pull request renames the files to typescript.

The actual changes are in this pull request: https://github.com/algolia/instantsearch.js/pull/4379

### CODE REVIEW

**Comment by yannickcr** [comment]
Seems you also need to rename some jest snapshots :wink:

**Comment by nunomaduro** [comment]
@yannickcr Those are ok with we loose the history right? I have done it on the second pull request.

**Comment by yannickcr** [comment]
@nunomaduro yes we are ok with loosing the history on these files, it was just to make the tests to pass.

But I don't know how "clean" you want this PR to be, because right now nothing is passing (tests, lint, type check :yum: )

**Comment by nunomaduro** [comment]
@yannickcr I see, this pull request is just file renaming. The important one is : https://github.com/algolia/instantsearch.js/pull/4379

**Comment by yannickcr** [comment]
As seen together, since everything is fixed in https://github.com/algolia/instantsearch.js/pull/4379 that will be merged just after this PR no need to fix this here :wink:

**Pull request merged**
