### PR TITLE
perf(hitsPerPageSelector): Use the correct lodash function

### PR DESCRIPTION
**Pull request by Jerskouille**
See https://github.com/algolia/instantsearch.js/pull/456/files#r43915199
Should make @bobylito happy :)

### CODE REVIEW

**Comment by redox** [comment]
I don't care about perf, but it's more readable :+1:

**Comment by Jerskouille** [comment]
Actually, that's the conventional changelog tag that fitted best with the commit I think. Should I use `style` in this kind of cases?

**Comment by redox** [comment]
> Should I use style in this kind of cases?

I think both are fine, I would personally go for either `style` or `chore` I think.

**Comment by vvo** [comment]
We can use "perf" if we actually made any siginficant perf improvment (and measured it).

**Pull request merged**
