### PR TITLE
chore(Template): Use cloneDeep with transformData

### LINKED ISSUE #683: Deep clone the object passed to transformData
For now, I've mostly used `transformData` to modify a specific attribute.
I think it makes more sense to pass a deep cloned version of the data object than the original one.

For instance, to make sure we're not messing with internal variables, for a price facet refinement, we'd have to do:

```js
{
  transformData: function(data) {
    return {
      isRefined: data.isRefined,
      name: '$' + data.name,
      count: data.count,
      etc.
    }
  }
}
```

or

```js
{
  transformData: function(data) {
    data = whatevercloningmethodwewant(data);
    data.name = '$' + data.name;
    return data;
  }
}
```

I'd like to easily be able to do:
```js
{
  transformData: function(data) {
    data.name = '$' + data.name;
    return data;
  }
}
```

It would be less error prone, and probably not resource consuming since we're using the original data if `transformData` hasn't been specified.
I'm opening this issue since I've been affected in my `currentRefinedValues` implementation, I modified the `name` value for the display and ended up screwing up my `onClick` handler which was using it.

### PR DESCRIPTION
**Pull request by Jerskouille**
Closes #683.

### CODE REVIEW

**Comment by Jerskouille** [comment]
I have no preference between `cloneDeep` and `JSON.parse(JSON.stringify(...))`, the former is probably more readable, and @bobylito mentionned something about `Date`s.

**Comment by vvo** [comment]
Can you add a test for this in the Template-test.js?

**Comment by vvo** [comment]
About cloneDeep versus JSON.parse(JSON.stringify()), let's wait for a performance issue before switching to it.

Also about dates etc.. We should be good since what comes from the helper is already JSON-SAFE data (= safe for JSON.parse/stringify)

**Comment by Jerskouille** [comment]
Data going to transformData doesn't have this guarantee.

**Comment by vvo** [comment]
:100:

**Pull request merged**
