### PR TITLE
chore(let): Use let instead of var

### LINKED ISSUE #391: Aren't we using `let` the wrong way?
In some widgets, `let` is used at the same level as `var`, and if I understood correctly it doesn't make sense.

Except if I didn't get the real purpose of `let` (which is, for me, to be used in conditions and loops), can we make it consistent?

### PR DESCRIPTION
**Pull request by Jerskouille**
Used `ag -l 'var ' widgets components decorators lib | xargs -I {} sed -i 's/var /let /g' {}` (ag is a grep-like, but faster).

Closes #391 .

### CODE REVIEW

**Comment by vvo** [comment]
:100: this is where having tests is a joy 👌

**Comment by pixelastic** [comment]
LGTM, but needs rebasing

**Comment by vvo** [comment]
Needs rebase also

**Comment by Jerskouille** [comment]
Done

**Comment by Jerskouille** [comment]
Done

**Comment by redox** [comment]
@pixelastic any chance `eslint` is able to help us on that, forcing us to use `let` instead of `var`?

:+1: @Jerskouille

**Comment by pixelastic** [comment]
@redox: https://github.com/algolia/instantsearch.js/pull/429 <= no more `var`

**Pull request merged**
