### PR TITLE
feat(numeric-selector): implement InstantSearch.css

### PR DESCRIPTION
**Pull request by francoischalifour**
## Specs

https://instantsearch-css.netlify.com/widgets/numeric-selector/

## Stories

https://deploy-preview-3130--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=NumericSelector.default

### CODE REVIEW

**Comment by bobylito** [comment]
Alternative stories are broken.

**Comment by francoischalifour** [comment]
They were already because we don't accept `undefined` values: https://community.algolia.com/instantsearch.js/v2/dev-novel/?selectedStory=NumericSelector.default

I'll fix that in this PR.

**Comment by francoischalifour** [comment]
I rebased to get your fix for the stories @bobylito ([see story](https://deploy-preview-3130--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=NumericSelector.with%20default%20value)).

**Comment by francoischalifour** [comment]
@Haroenv What is broken to you?

@samouss Oh, I wasn't aware. You can remove it in another PR, then.

**Comment by francoischalifour** [comment]
Closing in favor of #3183.

**Pull request closed without merging**
