### PR TITLE
style(require/from): Never use .js in requires and froms

### PR DESCRIPTION
**Pull request by Jerskouille**
For `require`s

```sh
ag -l "require\(.*.js.\)" | xargs -I {} sed -i -r '/(hogan|instantsearch)/! s#(require\(.*)\.js(.\))#\1\2#g' {}
```

For `import ... from ...`

```sh
ag -l "import .* from .*\.js" | xargs -I {} sed -i -r 's/(import.*from .*)\.js/\1/g' {}
```

Just here for consistency.

### CODE REVIEW

**Comment by redox** [comment]
:+1: @Jerskouille Next step would be to move from `require` to `Import` everywhere, unfortunately a `sed` command won't make it :)

**Comment by vvo** [comment]
Argh I should have linted this, the .js at the end of the file is important, so that you know from reading the code what are you requiring, a file, a directory..

**Comment by vvo** [comment]
Sorry, I fail at seeing the benefit of the change + since we are neither linting one or another solution then it will continue to pop out based on people preference

**Comment by redox** [comment]
> Argh I should have linted this, the .js at the end of the file is important, so that you know from reading the code what are you requiring, a file, a directory..

I didn't had that in mind; does it really change something?

**Comment by redox** [comment]
> since we are neither linting one or another solution

Good point; and because we need to use `require` inlined in some functions for the tests; it's not easy to lint (cannot find the rules anyway :/)

**Comment by vvo** [comment]
> I didn't had that in mind; does it really change something?

I guess it's just my own preference, no big deal

**Comment by vvo** [comment]
Let's discuss those changes next time, this is stylistic change we need to agree. Like removing semi colons

**Comment by Jerskouille** [comment]
I completely agree on this, I started this PR because of the differences in `lib/main.js` https://github.com/algolia/instantsearch.js/pull/710/files#diff-dbd1065ebaf59b9c5fec54631b2e5e06L10 where it was inconsistent. The path I chose was easily doable with sed, when the other way around wasn't.
I have no preference, I just love consistency.

**Comment by vvo** [comment]
> I have no preference, I just love consistency.

Like I do :D

I do have a preference you broke my dev :heart: (Kidding)

**Comment by pixelastic** [comment]
@vvo, where you suggesting something like?

- `require('foo')`: load global module `foo`
- `require('./foo'): load local module in `./foo/index.js`
- `require('./foo.js'): load local module in `./foo.js`

If so, I like the idea, to easily spot where we're requiring from, and make the magic more explicit. I'm not sure there is much convention agreed on that point in the community, and thus is an eslint rule exists. If no such rule exist, we should at least agree on the way to go and note it in the `CONTRIBUTING` so it is explicit.

**Comment by vvo** [comment]
I think we are going for the full version ('.js') for every local module since we try to never use "index.js". And @Jerskouille is finishing the algolia custom eslint rules for this :)

**Comment by pixelastic** [comment]
Oh nice @Jerskouille, I'm interested in how this looks like

**Comment by Jerskouille** [comment]
> require('foo'): load global module foo
> require('./foo'): load local module in./foo/index.js`
> require('./foo.js'): load local module in./foo.js`

That's exactly what the eslint rule I've made does :)

**Comment by vvo** [comment]
@Jerskouille So we can do require('./foo') AND require('./foo.js')? Or is it one or another version?

**Comment by Jerskouille** [comment]
You can require `./foo` if `./foo` exists, may it be a folder or a file. Else we throw an error `Relative require without extension`.

**Comment by vvo** [comment]
But if the file does not exists I do not understand the error

**Comment by vvo** [comment]
Why check for the file existence at all, its already done by other tools

**Comment by Jerskouille** [comment]
Because that's the easiest way to tell if the `require` was legitimate or not. Furthermore, if I didn't, files like `Object.freeze.js` would be detected as valid with `require(Object.freeze)`. (With webpack you can require almost any file extension so I didn't want it to be restrictive, so it accepts any file with a dot in its filename as valid -- except if it doesn't exist)

**Pull request merged**
