### PR TITLE
fix(Pit): round the middle value to the whole number

### PR DESCRIPTION
**Pull request by Haroenv**
Most prices start from > 0, which causes annoying decimal values at the middle.

This PR fixes that by always rounding the middle value to a whole number

Maybe not a complete fix for #2275, but definitely related to the underlying reason.

version|result
---|---
before|screen shot 2017-08-07 at 16 37 02
after|screen shot 2017-08-07 at 16 36 38

### CODE REVIEW

**Comment by Haroenv** [comment]
I wanted to add this as a prop first, but it seems like that might be hard with Rheostat

**Comment by iam4x** [comment]
When I did this, I wanted to correct the issues with the rangeSlider from v1 which was not placing the middle pit at the correct middle.

And also, to provide support for negatives values which was a nightmare for the v1.

What I purpose, is to use the `precision` parameter to know at what decimal we should round for the start/middle/end pit value.

What do you think?

**Comment by Haroenv** [comment]
Having this as an argument seems good to me. Precision as number of digits after 0, defaulting to 1?

**Comment by iam4x** [comment]
Yes exactly, the default value is 2 👍

**Comment by Haroenv** [comment]
Pit has now got a `precision` Prop, how do we expose it to the users, via `Slider`?

**Comment by bobylito** [comment]
@Haroenv what's the status on this? If you don't have time to take care of it for the moment, do you mind if I close the PR?

**Pull request closed without merging**
