### PR TITLE
chore: enable renovate automerge

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by vvo** [comment]
You only need:

```json
{
  "extends": ["config:js-lib", "algolia"]
}
```

It will automerge minor and patch by default

**Comment by bobylito** [comment]
> You only need:

Where is it documented? @vvo

**Comment by Haroenv** [comment]
https://github.com/algolia/renovate-config-algolia#whats-inside-the-configuration @bobylito

**Comment by bobylito** [comment]
Thanks for the infos @Haroenv @vvo

**Comment by bobylito** [comment]
Well it's not that important after all.

**Pull request closed without merging**
