### PR TITLE
fix(refinementList): Remove `singleRefine` attribute

### LINKED ISSUE #220: API proposal : Remove singleRefine from RefinementList
It seems to me that this parameter is redundant with the menu.

Since the menu is already handling disjunctive + single refine, it is here only for conjunctive faceting.
We have two options:
- If we're considering single value attributes => Then it's already the only refinement displayed
- If we're considering array attributes => Then why limit the user in his filtering abilities ?

### PR DESCRIPTION
**Pull request by pixelastic**
Fixes #220

This also more explicitly set the default operator to `or`.

### CODE REVIEW

**Comment by pixelastic** [comment]
Anyone?

**Comment by bobylito** [comment]
Let me have a look!

**Comment by bobylito** [comment]
Perfect! :+1:

**Comment by vvo** [comment]
YAY. No big deal but try to always set "BREAKING CHANGE". It will be a good habit once we are in production :)

**Comment by vvo** [comment]
And even right now, for the next changelog, it will be easy if we have "breaking change" lines to talk with integrations people

**Comment by pixelastic** [comment]
Yes, you're right sorry. I've added a comment in my default git commit message so I remember it :)

**Pull request merged**
