### PR TITLE
Fix no results for the hit widget

### PR DESCRIPTION
**Pull request by maxiloc**

### CODE REVIEW

**Comment by vvo** [comment]
Can you ammend commit first line to follow conventional changelog? (https://github.com/algolia/instantsearch.js/blob/develop/CONTRIBUTING.md)

```text
feat(hits): pass the full results to the noResultsTemplate
```

You'll get used to it :)

**Comment by maxiloc** [comment]
Good ?

**Comment by redox** [comment]
> Good ?

better with full sentence ;) "no results" isn't very explicit

**Comment by maxiloc** [comment]
Sure :smile:

**Pull request merged**
