### PR TITLE
Fix #411 bottom left panel links

### LINKED ISSUE #411: Documentation: bottom left links are redundant/taking too much space?
2015-11-02-184805_335x670_scrot

I am talking about the octocat/fork/stackoverflow icons.

Right now they are sticky to the documentation and are taking a good visual spot/place. But as a developer I would only need to see the octocat in the top right of the top menu.

Also the fork and octocat are redirecting to the same thing, and even "fixing" the fork button to actually fork the project would be weird.

You never really want to fork from a website that is not github, you just want to see the github project and browse it first.

I would put the octocat in top right and allow this space to be used for the left menu. Also the left menu will at some point take more height space so it will start looking weird as a fixed position menu.

What do you think?

### PR DESCRIPTION
**Pull request by bobylito**
Also fixes the toc_generator missing last `</ul>`

### CODE REVIEW

**Comment by redox** [comment]
Hmmm, I prefer how it was before; not sure about #411 either.

**Comment by vvo** [comment]
The provided screenshot is nice. We need a big top right github button still to easily give access to the github repo

**Comment by vvo** [comment]
In the end a fixed left menu only work if you limit the left menu items to a fixed number. The more they grow the more it will be hard to fit them all in the left column.

As for #411 I think I put what seemed obvious to me in it: big buttons at important spot while most users will not need them. Yes we need to show we are on github, not at a fixed css position I feel.

**Comment by redox** [comment]
> The provided screenshot is nice

I disagree, having the stackoverflow button "hidden" at the bottom of the menu doesn't make sense.

**Comment by vvo** [comment]
> I disagree, having the stackoverflow button "hidden" at the bottom of the menu doesn't make sense.

Yes ok.

TBH I think I do not see the exact value of linking to stackoverflow since I would first go to github issues. I would have a hard time deciding if I need to post on stackoverflow OR github since I have both links.

**Comment by bobylito** [comment]
The most common reflex for developers is to go to stackoverflow, I think. Not much people go for github to get their problem fixed.

**Comment by vvo** [comment]
> The most common reflex for developers is to go to stackoverflow, I think. Not much people go for github to get their problem fixed.

Yes but would you use the instantsearch documentation website to then click on stackoverflow icon?

**Comment by bobylito** [comment]
No :)

**Comment by bobylito** [comment]
https://www.dropbox.com/s/1y4vzhp34t0gtg9/Screenshot%202015-11-02%2014.21.50.png?dl=0

**Comment by vvo** [comment]
LGTM (:trollface:)

**Pull request merged**
