### PR TITLE
Added missing bracket on line 215

### PR DESCRIPTION
**Pull request by shalomvolchok**
Missing bracket in react-instantsearch docs.

### CODE REVIEW

**Comment by vvo** [comment]
Nice! Did you use the "edit this page" link?

**Comment by shalomvolchok** [comment]
Yes, used the 'edit this page' link. Took about 45 seconds...

**Comment by shalomvolchok** [comment]
I also noticed the next link at the bottom of `Default_refinements.md` leads to a 404. Wasn't sure where you wanted that to go, so didn't try and fix...

**Comment by vvo** [comment]
should go here: Searching_in_Lists.html

**Comment by vvo** [comment]
Can you submit another PR @shalomvolchok? THanks!

**Pull request merged**
