### PR TITLE
style(example): look & feel enhancement & simplifications

### PR DESCRIPTION
**Pull request by redox**
I started with something minimal: gif

### CODE REVIEW

**Comment by vvo** [comment]
Showing off!!

**Comment by vvo** [comment]
Woah you removed good templates, was it easy in the end?

**Comment by redox** [comment]
> you removed good templates

Yes I'm convinced most use-case won't specify templates for those widgets so I just wanted to ensure it's easy without.

> Woah you removed good templates, was it easy in the end?

I would say so-so because of such CSS rules like `.ais-menu--item__active .facet-value, .facet-value:hover, .ais-refinement-list--item__active .ais-refinement-list--label, .ais-hierarchical-menu--item__active > div > .facet-value {...}` => very hard to "share" behavior because of BEM. We'll need to iterate for v1.0 :) (cc @pixelastic)

**Comment by vvo** [comment]
> I would say so-so because of such CSS rules like .ais-menu--item__active .facet-value, .facet-value:hover, .ais-refinement-list--item__active .ais-refinement-list--label, .ais-hierarchical-menu--item__active > div > .facet-value {...} => very hard to "share" behavior because of BEM. We'll need to iterate for v1.0 :) (cc @pixelastic)

Ok let's talk about it in another issue soon

**Comment by redox** [comment]
> Ok let's talk about it in another issue soon

I managed to improved it in exchange of more JS code. Maybe acceptable :)

Let's see when building new the Amazon-like theme :) (cc @kokliKo)

**Comment by pixelastic** [comment]
@redox: At first I thought we could add more generic classes to all elements that inherit from refinementList. 

But `.ais-hierarchical-menu--item__active > div > .facet-value` is very weird. I'm surprise you had to resort to such a selector.

**Comment by redox** [comment]
> I'm surprised you had to resort to such a selector.

I've updated the PR and it's really not optimal. The behavior I want to implement is making bold the labels of every single facet (be it menu, refinement list or toggle) when you hover or refined them. All of that without custom template obviously :)

**Comment by pixelastic** [comment]
But you don't need `> div >` for that. The divs are just React `noise`, this should not be reflected in the selectors.

**Comment by redox** [comment]
> But you don't need > div > for that. The divs are just React noise, this should not be reflected in the selectors.

I need the div because I want to highlight the first child `<label>` only.

**Comment by vvo** [comment]
LGTM

**Comment by pixelastic** [comment]
> I need the div because I want to highlight the first child <label> only.

Might be an issue if we need this kind of workaround. The fact that we use React should stay internal and not pop up to the stylesheets.

**Pull request merged**
