### PR TITLE
Feat/menu select widget

### PR DESCRIPTION
**Pull request by iam4x**
I'm opening this PR to keep track progress of the `menuSelect` widget.

* [x] displays current refined value
* [x] update results after new selected refined value
* [x] rename `RefinementSelect` to `menuSelect` (needs to get some input from the team about naming)
* [x] tests 
* [x] documentation & examples

**What project are you opening a pull request for?**
- instantsearch.js (use develop base)

**Summary**
https://github.com/algolia/instantsearch.js/issues/868

**Result**

### CODE REVIEW

**Comment by vvo** [comment]
Deploy preview ready!

Built with commit edb6fe25b417ef64ed408bcdf67c2c595a5bb124

https://deploy-preview-2045--algolia-instantsearch.netlify.com

**Comment by iam4x** [comment]
I've rebased on `develop` to make it possible to merge 👍

**Comment by bobylito** [comment]
This will be a community widget. Thanks for the contribution.

**Comment by psren** [comment]
Is it already available somehow?

**Comment by Haroenv** [comment]
@psren, check out https://github.com/algolia/instantsearch.js/blob/develop/dev/app/custom-widgets/vanilla/selectMenu.js

**Comment by vvo** [comment]
Seems that some good gems are only available in the dev app, should we make them available via recipes or something?

**Comment by Haroenv** [comment]
We were thinking of getting the dev app visible for sure, a nice way would be to link to the source from the published dev novel @vvo 

cc @iam4x

**Comment by bobylito** [comment]
The menu select rendering is the example of the connectMenu: https://community.algolia.com/instantsearch.js/v2/connectors/connectMenu.html

**Pull request closed without merging**
