### PR TITLE
fix(pagination): always transition state

### LINKED ISSUE #1287: When clicking on the current page, search should not go back to the first one (no toggle)
This is an example of this behaviour on the tourism example.

pagination-revert-bug

### PR DESCRIPTION
**Pull request by bobylito**
fix #1287

### CODE REVIEW

**Comment by Morhaus** [comment]
This is the behavior that clears the page when the state changes from somewhere else than the pagination widget. For instance, to go back to page 0 when we add a refinement.

**Comment by Morhaus** [comment]
If you remove this behavior and implement it differently, you can clear all code related to transitionState since that is the only place where it's being used.

**Comment by vvo** [comment]
Owww @bobylito Maybe we need to revert and find a different approach?

**Comment by Morhaus** [comment]
What issue did you meet with this implementation of transitionState.

**Comment by vvo** [comment]
> What issue did you meet with this implementation of transitionState.

When page 2 is selected, if you select it again it removes the current page and goes to one. Maybe we need some special handling on it and that's it.

But it should be at the implementation side perhaps, not the connector

**Comment by vvo** [comment]
cc @bobylito did you have a look?

**Comment by bobylito** [comment]
I will have a look :) Sorry for the lag :)

**Pull request merged**
