### PR TITLE
fix(index-selector): Fix tests passing with incorrect parameters

### PR DESCRIPTION
**Pull request by Jerskouille**

### CODE REVIEW

**Comment by pixelastic** [comment]
Can you add a test that check that passing `['indexA', 'indexB']` (ie. not array of objects) should fail, as expected?

**Comment by redox** [comment]
> Can you add a test that check that passing ['indexA', 'indexB'] (ie. not array of objects) should fail, as expected?

I think that's really related to https://github.com/algolia/instantsearch.js/issues/309#issuecomment-149864298 => tldr; I don't think we want to re-implement all checks React is providing in dev :/

**Comment by Jerskouille** [comment]
I will add a test checking that we correctly send back an error if there is no attribute `name` in the object.

**Comment by pixelastic** [comment]
My point was not about re-testing the correct props. I agree that we should use the tooling we already have.

My point was that we had a test that was passing when it should have failed. So now that we are fixing it, we should add a test, to make sure we do not introduce any regression later, like for any other feature.

**Comment by Jerskouille** [comment]
I agree with you @pixelastic , except in the case where we're not respecting our own documentation. But having a larger test that will at the same time cover this is a good solution IMHO.

**Comment by pixelastic** [comment]
Yep, makes sense, we were not even following our own documentation here, so bugs were expected. I agree the test I was suggesting is not really needed.

**Comment by vvo** [comment]
@Jerskouille are we good here?

**Comment by Jerskouille** [comment]
@vvo Yes, I think so.

**Pull request merged**
