### PR TITLE
docs: update banner

### PR DESCRIPTION
**Pull request by eunjae-lee**
**Summary**

This PR updates the banner image.
More context [here](https://algolia.slack.com/archives/CA1KWSXU2/p1565698069004900)

**Result**

[View rendered](https://github.com/algolia/instantsearch.js/blob/272c7e66ca1ac7b38ac1fdbb2e63a05d9593380e/README.md)

### CODE REVIEW

**Comment by francoischalifour** [comment]
Let's wait for [these comments](https://app.asana.com/0/526444548795226/1135487054018576) to be addressed before merging (wording + shadow).

**Comment by francoischalifour** [comment]
Closing this – waiting for the final banner.

**Comment by eunjae-lee** [comment]
oh did we get the new one?

**Comment by francoischalifour** [comment]
This is still not the right banner. I'm in contact with Tiphaine and added the drop shadow. I'm sending a PR rn.

**Comment by Haroenv** [comment]
I don't see which shadow you mean, but i trust you @francoischalifour  :)

**Comment by eunjae-lee** [comment]
image

**Pull request closed without merging**
