### PR TITLE
DO NOT MERGE: fixing the develop branch

### PR DESCRIPTION
**Pull request by tkrugg**
If we all agree this diff is correct for the latest changes on develop, let's reset --hard develop be done with it :)

@Haroenv can you help checking the diff as you had contributions on develop lately?

### CODE REVIEW

**Comment by francoischalifour** [comment]
Can you give more context here? Do you want to update the `master` branch because the release script is unable to catch up?

**Comment by tkrugg** [comment]
there was some hick up on the v4 release that messed up the history on  `develop`. 
This `develop__` branch is meant the be the fixed history and replace the current `develop`.

**Comment by yannickcr** [comment]
I'd also like more information here. Can you explain more in details what was the issue with the develop branch? And what you did to resolve it?

**Comment by tkrugg** [comment]
The issue is some commit have been rewritten as a result of a bad manipulation.
It's obvious when looking at https://github.com/algolia/instantsearch.js/compare/master...develop.
What I did is look at the history of the branch, go back to the latest merge with master and remove all the priori commits (duplicate commits).
Does this clarify?

**Comment by Haroenv** [comment]
as far as I can tell this is the correct commits which happen after v4.0.0

**Comment by francoischalifour** [comment]
I still don't fully understand what you intend to do. If you look at the commits history, it's messed up even before the 4.0.0 release. There are plenty of duplicates before 92b07d15332adbb16908d6771fe0f1083fae2de4:

- https://github.com/algolia/instantsearch.js/commits/develop?before=921f80530e1289bcab2850b000a899dcf64aae95+70
- https://github.com/algolia/instantsearch.js/commits/develop?after=921f80530e1289bcab2850b000a899dcf64aae95+174

Look for "feat(places): add Places widget" for instance.

**Comment by tkrugg** [comment]
@francoischalifour my intention is to make develop operable again. 
We currently can't deploy because develop cannot be merged on master.
The places commits appearing twice is not troubling since they appear before the merge commit with master.

**Comment by francoischalifour** [comment]
Right – make sure to take into account the 2 last commits from `develop` before operating.

**Comment by tkrugg** [comment]
it's done!

**Pull request closed without merging**
