### PR TITLE
test(lib/InstantSearch): test using mocha, expect

### PR DESCRIPTION
**Pull request by vvo**
+ move validate commit message in travis.yml only. Most of the time
you will not run npm test AFTER committing but before, thus no need
for local check
+ remove unneeded .sh scripts, if there's one command words then no
need for a full sh script
+ development workflow precisions in readme

### CODE REVIEW

**Comment by vvo** [comment]
Waiting for a new sinon.js release to be able to remove the github dep

**Comment by vvo** [comment]
giphy 1

**Comment by redox** [comment]
LGTM :+1:

**Comment by pixelastic** [comment]
> Waiting for a new sinon.js release to be able to remove the github dep

Except for that, LGTM

**Pull request merged**
