### PR TITLE
docs(code samples): change syntax theme, add copy button

### PR DESCRIPTION
**Pull request by vvo**
This commit changes the syntax theme to use GitHub colors and adds a
little header much like on reactjs docs.

It also adds a copy button.

Before:
image

After:
image

Also this:
image

Copy button:
copy-paste

### CODE REVIEW

**Comment by bobylito** [comment]
Is it possible to style the copy button? :)

**Comment by vvo** [comment]
Yes, I wondered if maybe a simpler text only button could do it and would be more obvious:

```
[ COPY ]
```

```
[ COPIED ! ]
```

?

**Comment by vvo** [comment]
RIght now this is just an SVG I took from https://clipboardjs.com/ (and it's the same as on GitHub clone copy icon)

**Comment by vvo** [comment]
Ok we are good

**Comment by bobylito** [comment]
\o/

**Pull request merged**
