### PR TITLE
chore(pkg) fix Algolia name

### PR DESCRIPTION
**Pull request by Haroenv**
**What project are you opening a pull request for?**
- react-instantsearch (use v2 base)

**Summary**

As far as I know we always use Algolia SAS, since that's our actual financial "title", or do we have an Inc. too?

**Result**

package.json now contains Algolia SAS as the author name

### CODE REVIEW

**Comment by vvo** [comment]
Deploy preview ready!

Built with commit 344a50d79193f74d771eb66a93a84a3c75819a07

https://deploy-preview-2060--algolia-instantsearch.netlify.com

**Comment by rayrutjes** [comment]
I think SAS is in France and Inc. in the US.

**Comment by redox** [comment]
We want to keep `Inc`, reflecting as @rayrutjes mentioned, our US-based HQ.

**Comment by Haroenv** [comment]
All right, sorry for the confusion, was just the first time I saw Inc.

**Comment by vvo** [comment]
Started putting , Inc. recently

**Pull request closed without merging**
