### PR TITLE
style(scss): Convert sass to scss, add linting to docs

### PR DESCRIPTION
**Pull request by pixelastic**
This is the start of the fix of #538. I managed to make the linting work on the docs css files, but we'll now have to fix the linting issues.

- [x] Renamed all `sass` files to `scss`
- [x] Applied linting to all `scss` files, excluding the vendors
- [x] Created `main.scss` files in `examples` that includes the required front-matter (lines starting with `---`, needed by Jekyll). Those files only `@import` the real `style.scss` and are excluded from the linting process
- [x] Split lint tasks into `npm run lint:js` and `npm run lint:css`

I now need feedback to see if that's the right track (cc @redox) and we'll then need to fix all the styling issues of the scss files.

### CODE REVIEW

**Comment by Shipow** [comment]
no plz don't do that....

**Comment by pixelastic** [comment]
Don't do what? Could you elaborate?

**Comment by Shipow** [comment]
don't convert sass to scss, at least until I haven't finished to work on it plz.

**Comment by pixelastic** [comment]
Yep, sure, this is a work in progress. We'll not merge it until you're finished don't worry :)

**Comment by bobylito** [comment]
I like the idea (but I feel for @Shipow :D)

**Comment by pixelastic** [comment]
I've rebased on 1.0.0. Tests are failing because...
image

**Comment by pixelastic** [comment]
I was thinking waiting a few days, until the release is over, and then fix all the linting issues

**Comment by vvo** [comment]
@pixelastic do you want to move forward with this one?

**Comment by pixelastic** [comment]
I would like us to have some Travis testing on SCSS for the website, so we cannot push things that will break.

But this means fixing all the SCSS lint issues, which can be quite long. I'm not sure I'll have time to do it in the next two weeks, but I can do it afterwards.

**Comment by vvo** [comment]
Ok do you agree on closing this one and reopen it when relevant?

**Comment by Shipow** [comment]
@pixelastic can you copy the outpout of this scss warnings ?

**Comment by pixelastic** [comment]
@vvo: Yep, we can close this one

@Shipow: Here is the output

```

> instantsearch.js@1.0.0 lint:css /home/tim/local/www/algolia/javascript/instantsearch.js
> sass-lint --verbose


docs/css/_animation.scss
  14:3  warning  Rule `0` should be merged with the rule on line 4    no-mergeable-selectors
  17:3  warning  Rule `100` should be merged with the rule on line 7  no-mergeable-selectors
  24:3  warning  Rule `0` should be merged with the rule on line 4    no-mergeable-selectors
  28:3  warning  Rule `100` should be merged with the rule on line 7  no-mergeable-selectors
  36:3  warning  Rule `0` should be merged with the rule on line 4    no-mergeable-selectors
  40:3  warning  Rule `100` should be merged with the rule on line 7  no-mergeable-selectors
  48:3  warning  Rule `100` should be merged with the rule on line 7  no-mergeable-selectors

docs/css/_base.scss
   7:17  error    Hex notation should all be upper case                            hex-notation
   8:14  error    Hex notation should all be upper case                            hex-notation
  10:19  warning  Color 'black' should be written in its hexadecimal form #000000  no-color-keywords
  10:26  warning  Don't include leading zeros on numbers                           leading-zero
  14:17  error    Hex notation should all be upper case                            hex-notation
  15:14  error    Hex notation should all be upper case                            hex-notation
  16:13  error    Hex notation should all be upper case                            hex-notation
  19:19  warning  Color 'green' should be written in its hexadecimal form #008000  no-color-keywords

docs/css/_documentation.scss
   28:13  warning  pseudoClass `:before` should be nested within its parent selector                                  force-pseudo-nesting
   45:18  warning  Don't include leading zeros on numbers                                                             leading-zero
   69:15  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
   69:22  warning  Don't include leading zeros on numbers                                                             leading-zero
   70:14  warning  Don't include leading zeros on numbers                                                             leading-zero
   81:28  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
   81:35  warning  Don't include leading zeros on numbers                                                             leading-zero
   86:7   warning  Duplicate properties are not allowed within a block                                                no-duplicate-properties
   97:22  warning  Don't include leading zeros on numbers                                                             leading-zero
  111:24  warning  Don't include leading zeros on numbers                                                             leading-zero
  115:5   warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  115:5   warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  115:13  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  115:13  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  115:21  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  115:21  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  118:5   warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  118:5   warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  118:13  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  118:13  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  118:21  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  118:21  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  118:29  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  118:29  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  118:37  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  118:37  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  125:6   warning  Qualifying elements are not allowed for class selectors                                            no-qualifying-elements
  127:18  warning  Don't include leading zeros on numbers                                                             leading-zero
  129:22  warning  Don't include leading zeros on numbers                                                             leading-zero
  130:20  warning  Don't include leading zeros on numbers                                                             leading-zero
  138:8   warning  Qualifying elements are not allowed for class selectors                                            no-qualifying-elements
  143:13  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  143:13  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  172:19  warning  Don't include leading zeros on numbers                                                             leading-zero
  178:31  error    Hex notation should all be upper case                                                              hex-notation
  180:13  warning  Property `margin` should be written more concisely as `2em 0 1em` instead of `2em 0 1em 0`         shorthand-values
  186:23  error    Hex notation should all be upper case                                                              hex-notation
  187:30  error    Hex notation should all be upper case                                                              hex-notation
  193:14  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
  197:15  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  202:16  warning  Don't include leading zeros on numbers                                                             leading-zero
  205:14  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
  215:11  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  216:10  error    Hex notation should all be upper case                                                              hex-notation
  219:21  error    Hex notation should all be upper case                                                              hex-notation
  227:21  error    Hex notation should all be upper case                                                              hex-notation
  242:23  error    Hex notation should all be upper case                                                              hex-notation
  244:20  warning  Property `border-radius` should be written more concisely as `5px 0 3px` instead of `5px 0 3px 0`  shorthand-values
  262:21  error    Hex notation should all be upper case                                                              hex-notation
  263:42  error    Hex notation should all be upper case                                                              hex-notation
  263:54  error    Hex notation should all be upper case                                                              hex-notation
  281:25  error    Hex notation should all be upper case                                                              hex-notation
  282:15  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  283:25  warning  Don't include leading zeros on numbers                                                             leading-zero
  283:48  warning  Don't include leading zeros on numbers                                                             leading-zero
  285:16  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
  288:18  warning  No unit allowed for values of 0                                                                    zero-unit
  301:16  warning  Don't include leading zeros on numbers                                                             leading-zero
  302:44  warning  Don't include leading zeros on numbers                                                             leading-zero
  303:13  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  305:17  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
  305:24  warning  Don't include leading zeros on numbers                                                             leading-zero
  306:25  warning  Don't include leading zeros on numbers                                                             leading-zero
  308:16  warning  No unit allowed for values of 0                                                                    zero-unit
  311:14  error    Hex notation should all be upper case                                                              hex-notation
  313:21  error    Hex notation should all be upper case                                                              hex-notation
  323:13  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  324:12  error    Hex notation should all be upper case                                                              hex-notation
  327:23  error    Hex notation should all be upper case                                                              hex-notation
  329:25  error    Hex notation should all be upper case                                                              hex-notation
  332:14  error    Hex notation should all be upper case                                                              hex-notation
  339:18  warning  Don't include leading zeros on numbers                                                             leading-zero
  344:14  error    Hex notation should all be upper case                                                              hex-notation
  348:15  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  363:18  warning  Don't include leading zeros on numbers                                                             leading-zero
  364:34  error    Hex notation should all be upper case                                                              hex-notation
  366:18  warning  Color 'white' should be written in its hexadecimal form #ffffff                                    no-color-keywords
  376:16  error    Hex notation should all be upper case                                                              hex-notation
  382:13  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  383:12  error    Hex notation should all be upper case                                                              hex-notation
  386:23  error    Hex notation should all be upper case                                                              hex-notation
  390:14  error    Hex notation should all be upper case                                                              hex-notation
  405:10  error    Hex notation should all be upper case                                                              hex-notation
  411:21  warning  pseudoClass `:after` should be nested within its parent class                                      force-pseudo-nesting
  413:13  warning  A value of `none` is not allowed. `0` must be used                                                 border-zero
  443:9   warning  Duplicate properties are not allowed within a block                                                no-duplicate-properties
  465:30  error    Hex notation should all be upper case                                                              hex-notation
  467:20  error    Hex notation should all be upper case                                                              hex-notation
  472:32  error    Hex notation should all be upper case                                                              hex-notation
  474:22  error    Hex notation should all be upper case                                                              hex-notation
  480:10  warning  pseudoClass `:hover` should be nested within its parent selector                                   force-pseudo-nesting
  483:12  warning  attribute `[class^=ais-]` should be nested within its parent selector                              force-attribute-nesting
  483:12  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  483:25  warning  pseudoClass `:hover` should be nested within its parent attribute                                  force-pseudo-nesting
  488:12  warning  attribute `[class^=ais-]` should be nested within its parent selector                              force-attribute-nesting
  488:12  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  488:25  warning  pseudoClass `:focus` should be nested within its parent attribute                                  force-pseudo-nesting
  488:38  warning  attribute `[class^=ais-]` should be nested within its parent selector                              force-attribute-nesting
  488:38  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  488:51  warning  pseudoClass `:active` should be nested within its parent attribute                                 force-pseudo-nesting
  498:3   warning  Rule `.main-documentation` should be merged with the rule on line 58                               no-mergeable-selectors
  499:14  warning  Property `padding` should be written more concisely as `60px 0 0` instead of `60px 0 0 0`          shorthand-values
  507:3   warning  Rule `.documentation-content` should be merged with the rule on line 108                           no-mergeable-selectors
  508:14  warning  Property `padding` should be written more concisely as `60px 0 0` instead of `60px 0 0 0`          shorthand-values
  509:16  warning  Don't include leading zeros on numbers                                                             leading-zero
  520:3   warning  Rule `.widget-description` should be merged with the rule on line 54                               no-mergeable-selectors
  528:3   warning  Rule `.widget-container` should be merged with the rule on line 225                                no-mergeable-selectors
  531:3   warning  Rule `.code-box` should be merged with the rule on line 269                                        no-mergeable-selectors
  533:17  error    Hex notation should all be upper case                                                              hex-notation
  535:5   warning  Rule `.btn-group` should be merged with the rule on line 274                                       no-mergeable-selectors
  538:5   warning  Rule `.copy-btn` should be merged with the rule on line 295                                        no-mergeable-selectors
  542:5   warning  Rule `.btn-group` should be merged with the rule on line 274                                       no-mergeable-selectors
  543:7   warning  Rule `.toggle-doc-button` should be merged with the rule on line 278                               no-mergeable-selectors
  545:9   warning  Rule `&.active` should be merged with the rule on line 290                                         no-mergeable-selectors
  546:23  error    Hex notation should all be upper case                                                              hex-notation
  550:5   warning  Rule `.jsdoc` should be merged with the rule on line 322                                           no-mergeable-selectors
  554:3   warning  Rule `.widget-description` should be merged with the rule on line 54                               no-mergeable-selectors
  555:5   warning  Property `overflow-scrolling` appears to be spelled incorrectly                                    no-misspelled-properties
  555:5   warning  Vendor prefixes should not be used                                                                 no-vendor-prefixes
  557:27  warning  attribute `[id]` should be nested within its parent selector                                       force-attribute-nesting
  557:27  warning  Qualifying elements are not allowed for attribute selectors                                        no-qualifying-elements
  562:5   warning  Rule `p,  h1,  h2,  h3,  h4` should be merged with the rule on line 521                            no-mergeable-selectors

docs/css/_footer.scss
  1:7   warning  Qualifying elements are not allowed for class selectors          no-qualifying-elements
  5:21  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  8:12  error    Hex notation should all be upper case                            hex-notation

docs/css/_header.scss
   1:7   warning  Qualifying elements are not allowed for class selectors          no-qualifying-elements
   6:46  error    Hex notation should all be upper case                            hex-notation
   6:55  warning  Don't include leading zeros on numbers                           leading-zero
   6:71  error    Hex notation should all be upper case                            hex-notation
   6:80  warning  Don't include leading zeros on numbers                           leading-zero
   8:6   warning  Qualifying elements are not allowed for class selectors          no-qualifying-elements
  10:23  error    Hex notation should all be upper case                            hex-notation
  12:13  warning  A value of `none` is not allowed. `0` must be used               border-zero
  14:25  error    Hex notation should all be upper case                            hex-notation
  14:33  warning  !important not allowed                                           no-important
  15:27  warning  Don't include leading zeros on numbers                           leading-zero
  26:14  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  36:14  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  39:32  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  39:39  warning  Don't include leading zeros on numbers                           leading-zero
  40:16  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  48:16  error    Hex notation should all be upper case                            hex-notation
  48:24  warning  !important not allowed                                           no-important

docs/css/_helper.scss
  425:25  warning  !important not allowed                                           no-important
  426:26  warning  !important not allowed                                           no-important
  466:29  warning  !important not allowed                                           no-important
  486:26  error    Hex notation should all be upper case                            hex-notation
  491:27  error    Hex notation should all be upper case                            hex-notation
  505:12  warning  Don't include leading zeros on numbers                           leading-zero
  517:9   warning  Don't include leading zeros on numbers                           leading-zero
  521:12  warning  Don't include leading zeros on numbers                           leading-zero
  525:17  warning  !important not allowed                                           no-important
  529:10  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  533:21  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords

docs/css/_home.scss
   16:12  warning  Don't include leading zeros on numbers                           leading-zero
   21:9   warning  Qualifying elements are not allowed for class selectors          no-qualifying-elements
   21:25  warning  Qualifying elements are not allowed for class selectors          no-qualifying-elements
   22:28  warning  Color 'black' should be written in its hexadecimal form #000000  no-color-keywords
   41:53  warning  Don't include leading zeros on numbers                           leading-zero
   41:84  error    Hex notation should all be upper case                            hex-notation
   62:10  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
   79:15  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
   79:22  warning  Don't include leading zeros on numbers                           leading-zero
   81:12  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
   82:35  error    Hex notation should all be upper case                            hex-notation
   82:44  warning  Don't include leading zeros on numbers                           leading-zero
   83:13  warning  No empty blocks allowed                                          no-empty-rulesets
   89:15  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
   89:22  warning  Don't include leading zeros on numbers                           leading-zero
   90:14  warning  Don't include leading zeros on numbers                           leading-zero
  102:11  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  111:21  error    Hex notation should all be upper case                            hex-notation
  121:10  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  173:21  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  181:28  error    Hex notation should all be upper case                            hex-notation
  181:37  warning  Don't include leading zeros on numbers                           leading-zero
  187:28  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords
  232:21  warning  Color 'white' should be written in its hexadecimal form #ffffff  no-color-keywords

docs/css/_mixin.scss
   9:4  warning  Vendor prefixes should not be used  no-vendor-prefixes
  13:4  warning  Vendor prefixes should not be used  no-vendor-prefixes
  17:4  warning  Vendor prefixes should not be used  no-vendor-prefixes

docs/css/_search.scss
  11:44  warning  Don't include leading zeros on numbers                                                         leading-zero
  12:5   warning  Duplicate properties are not allowed within a block                                            no-duplicate-properties
  15:12  warning  Color 'white' should be written in its hexadecimal form #ffffff                                no-color-keywords
  23:7   warning  The keyword `all` should not be used with the property `transition`                            no-transition-all
  23:23  warning  Don't include leading zeros on numbers                                                         leading-zero
  39:23  warning  Color 'white' should be written in its hexadecimal form #ffffff                                no-color-keywords
  41:44  warning  Don't include leading zeros on numbers                                                         leading-zero
  45:18  warning  !important not allowed                                                                         no-important
  56:14  warning  Property `padding` should be written more concisely as `10px 0 2px` instead of `10px 0 2px 0`  shorthand-values
  65:44  warning  Don't include leading zeros on numbers                                                         leading-zero
  86:51  warning  Don't include leading zeros on numbers                                                         leading-zero
  92:38  warning  Don't include leading zeros on numbers                                                         leading-zero
  99:16  warning  Don't include leading zeros on numbers                                                         leading-zero

docs/examples/e-commerce/_style.scss
   32:5   warning  pseudoClass `:focus` should be nested within its parent selector                          force-pseudo-nesting
   42:12  warning  Whitespace required before {                                                              space-before-brace
   52:16  warning  Whitespace required before {                                                              space-before-brace
   82:10  warning  Whitespace required before {                                                              space-before-brace
   91:12  warning  Color 'white' should be written in its hexadecimal form #ffffff                           no-color-keywords
   92:11  warning  Whitespace required before {                                                              space-before-brace
  104:15  warning  A value of `none` is not allowed. `0` must be used                                        border-zero
  114:15  warning  A value of `none` is not allowed. `0` must be used                                        border-zero
  129:15  warning  Color 'white' should be written in its hexadecimal form #ffffff                           no-color-keywords
  133:13  warning  Property `margin` should be written more concisely as `0 0 8px` instead of `0 0 8px 0`    shorthand-values
  135:16  warning  Whitespace required before {                                                              space-before-brace
  141:8   warning  Whitespace required before {                                                              space-before-brace
  144:14  warning  Whitespace required before {                                                              space-before-brace
  146:13  warning  Property `margin` should be written more concisely as `4px 0` instead of `4px 0 4px 0`    shorthand-values
  149:12  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  154:12  warning  Whitespace required before {                                                              space-before-brace
  157:9   warning  Whitespace required before {                                                              space-before-brace
  161:13  warning  Whitespace required before {                                                              space-before-brace
  168:14  warning  Whitespace required before {                                                              space-before-brace
  175:14  warning  Whitespace required before {                                                              space-before-brace
  183:13  warning  Whitespace required before {                                                              space-before-brace
  184:40  warning  Color 'white' should be written in its hexadecimal form #ffffff                           no-color-keywords
  186:31  warning  Whitespace required before {                                                              space-before-brace
  187:25  warning  Color 'white' should be written in its hexadecimal form #ffffff                           no-color-keywords
  189:15  warning  Whitespace required before {                                                              space-before-brace
  190:42  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  193:6   warning  Indentation of 5, expected 4                                                              indentation
  193:32  warning  Whitespace required before {                                                              space-before-brace
  194:25  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  196:6   warning  Indentation of 5, expected 4                                                              indentation
  196:38  warning  Whitespace required before {                                                              space-before-brace
  199:30  warning  Whitespace required before {                                                              space-before-brace
  202:7   warning  Indentation of 6, expected 4                                                              indentation
  202:32  warning  Whitespace required before {                                                              space-before-brace
  205:7   warning  Indentation of 6, expected 4                                                              indentation
  205:32  warning  Whitespace required before {                                                              space-before-brace
  208:7   warning  Indentation of 6, expected 4                                                              indentation
  208:33  warning  Whitespace required before {                                                              space-before-brace
  211:7   warning  Indentation of 6, expected 4                                                              indentation
  211:33  warning  Whitespace required before {                                                              space-before-brace
  214:5   warning  Rule `&[data-facet-value="Brown"]` should be merged with the rule on line 211             no-mergeable-selectors
  214:31  warning  Whitespace required before {                                                              space-before-brace
  217:29  warning  Whitespace required before {                                                              space-before-brace
  220:35  warning  Whitespace required before {                                                              space-before-brace
  223:38  warning  Whitespace required before {                                                              space-before-brace
  226:37  warning  Whitespace required before {                                                              space-before-brace
  229:43  warning  Whitespace required before {                                                              space-before-brace
  232:35  warning  Whitespace required before {                                                              space-before-brace
  235:31  warning  Whitespace required before {                                                              space-before-brace
  238:37  warning  Whitespace required before {                                                              space-before-brace
  241:37  warning  Whitespace required before {                                                              space-before-brace
  244:35  warning  Whitespace required before {                                                              space-before-brace
  247:38  warning  Whitespace required before {                                                              space-before-brace
  250:32  warning  Whitespace required before {                                                              space-before-brace
  253:35  warning  Whitespace required before {                                                              space-before-brace
  256:6   warning  Indentation of 5, expected 4                                                              indentation
  256:37  warning  Whitespace required before {                                                              space-before-brace
  259:31  warning  Whitespace required before {                                                              space-before-brace
  262:36  warning  Whitespace required before {                                                              space-before-brace
  265:41  warning  Whitespace required before {                                                              space-before-brace
  268:36  warning  Whitespace required before {                                                              space-before-brace
  271:35  warning  Whitespace required before {                                                              space-before-brace
  274:31  warning  Whitespace required before {                                                              space-before-brace
  277:37  warning  Whitespace required before {                                                              space-before-brace
  280:37  warning  Whitespace required before {                                                              space-before-brace
  283:50  warning  Whitespace required before {                                                              space-before-brace
  288:25  warning  Whitespace required before {                                                              space-before-brace
  302:27  warning  Whitespace required before {                                                              space-before-brace
  317:25  warning  Color 'white' should be written in its hexadecimal form #ffffff                           no-color-keywords
  338:7   warning  Whitespace required before {                                                              space-before-brace
  342:19  warning  Whitespace required before {                                                              space-before-brace
  347:10  warning  Whitespace required before {                                                              space-before-brace
  373:42  warning  Commas should be followed by a space                                                      space-after-comma
  375:27  warning  Whitespace required before {                                                              space-before-brace
  390:46  warning  Don't include leading zeros on numbers                                                    leading-zero
  390:55  warning  Don't include leading zeros on numbers                                                    leading-zero
  393:32  warning  Whitespace required before {                                                              space-before-brace
  406:5   warning  Duplicate properties are not allowed within a block                                       no-duplicate-properties
  406:12  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  408:13  warning  Property `margin` should be written more concisely as `0 0 8px` instead of `0 0 8px 0`    shorthand-values
  413:13  warning  Property `margin` should be written more concisely as `0 0 10px` instead of `0 0 10px 0`  shorthand-values
  414:25  warning  Commas should be followed by a space                                                      space-after-comma
  423:12  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  428:12  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  428:18  warning  !important not allowed                                                                    no-important
  441:33  warning  Whitespace required before {                                                              space-before-brace
  442:12  warning  Color 'black' should be written in its hexadecimal form #000000                           no-color-keywords
  445:33  warning  Whitespace required before {                                                              space-before-brace
  448:32  warning  Commas should be followed by a space                                                      space-after-comma
  449:13  warning  Whitespace required before {                                                              space-before-brace
  462:4   warning  Qualifying elements are not allowed for class selectors                                   no-qualifying-elements
  470:14  warning  Don't include leading zeros on numbers                                                    leading-zero

docs/examples/media/_style.scss
   26:8   warning  Whitespace required before {                                                            space-before-brace
   35:9   warning  Whitespace required before {                                                            space-before-brace
  120:19  error    Hex notation should all be upper case                                                   hex-notation
  132:17  warning  Property `margin` should be written more concisely as `0 0 1px` instead of `0 0 1px 0`  shorthand-values
  141:13  warning  Whitespace required before {                                                            space-before-brace
  157:28  warning  pseudoClass `:hover` should be nested within its parent class                           force-pseudo-nesting
  157:57  warning  pseudoClass `:active` should be nested within its parent class                          force-pseudo-nesting
  157:87  warning  pseudoClass `:focus` should be nested within its parent class                           force-pseudo-nesting
  163:28  warning  Whitespace required before {                                                            space-before-brace
  213:25  error    Hex notation should all be upper case                                                   hex-notation
  241:16  warning  Don't include leading zeros on numbers                                                  leading-zero
  262:13  warning  Whitespace required before {                                                            space-before-brace
  263:15  error    Hex notation should all be upper case                                                   hex-notation

docs/examples/tourism/_style.scss
    3:25  error    Hex notation should all be upper case                               hex-notation
    4:22  error    Hex notation should all be upper case                               hex-notation
    6:23  error    Hex notation should all be upper case                               hex-notation
    7:28  error    Hex notation should all be upper case                               hex-notation
    8:30  error    Hex notation should all be upper case                               hex-notation
   33:7   warning  Qualifying elements are not allowed for class selectors             no-qualifying-elements
   36:54  warning  !important not allowed                                              no-important
   38:10  warning  Whitespace required before {                                        space-before-brace
   67:13  warning  A value of `none` is not allowed. `0` must be used                  border-zero
   99:16  warning  Don't include leading zeros on numbers                              leading-zero
  109:5   warning  Vendor prefixes should not be used                                  no-vendor-prefixes
  115:16  warning  pseudoClass `:before` should be nested within its parent class      force-pseudo-nesting
  125:12  error    Hex notation should all be upper case                               hex-notation
  137:20  warning  Don't include leading zeros on numbers                              leading-zero
  155:19  warning  Color 'white' should be written in its hexadecimal form #ffffff     no-color-keywords
  156:7   warning  Vendor prefixes should not be used                                  no-vendor-prefixes
  163:37  warning  pseudoClass `:before` should be nested within its parent class      force-pseudo-nesting
  169:16  error    Hex notation should all be upper case                               hex-notation
  183:31  warning  pseudoClass `:last-child` should be nested within its parent class  force-pseudo-nesting
  219:15  error    Hex notation should all be upper case                               hex-notation
  224:21  warning  Whitespace required before {                                        space-before-brace
  234:35  warning  Commas should be followed by a space                                space-after-comma
  234:39  warning  Commas should be followed by a space                                space-after-comma
  234:43  warning  Commas should be followed by a space                                space-after-comma
  279:23  warning  pseudoClass `:focus` should be nested within its parent selector    force-pseudo-nesting
  280:23  warning  pseudoClass `:hover` should be nested within its parent selector    force-pseudo-nesting
  281:26  warning  pseudoClass `:focus` should be nested within its parent selector    force-pseudo-nesting
  282:26  warning  pseudoClass `:hover` should be nested within its parent selector    force-pseudo-nesting
  284:42  warning  !important not allowed                                              no-important
  292:14  warning  Don't include leading zeros on numbers                              leading-zero
  294:12  error    Hex notation should all be upper case                               hex-notation

src/css/default/_star-rating.scss
  41:7  warning  Rule `&:before` should be merged with the rule on line 31  no-mergeable-selectors
  52:9  warning  Rule `&:before` should be merged with the rule on line 31  no-mergeable-selectors
  57:9  warning  Rule `&:before` should be merged with the rule on line 31  no-mergeable-selectors

✖ 348 problems (59 errors, 289 warnings)
```

**Comment by Shipow** [comment]
I had a look, I'm pretty confident it's quick and easy to fix.

**Comment by Shipow** [comment]
And I'll do it tomorrow afternoon CET because obviously I'll learn some rules :+1:

**Pull request closed without merging**
