### PR TITLE
feat(MultiRange): indicate if a range has no refinements

### PR DESCRIPTION
**Pull request by mthuret**
For the MultiRange, compute a boolean for each item range in order to add classes like:

image

### CODE REVIEW

**Comment by Kikobeats** [comment]
fast question, could be possible select more than option?

**Comment by mthuret** [comment]
@Kikobeats I'm not sure to fully understand your question, can give us more details?

**Comment by Kikobeats** [comment]
@mthuret sure, something like:

lol

pick more than one

**Comment by bobylito** [comment]
As of now it's not possible because of a limitation of the underlying JS Helper. I have an [issue opened there](https://github.com/algolia/algoliasearch-helper-js/issues/461) that would make this possible.

**Comment by Kikobeats** [comment]
hmm interesting! then I will waiting for that, thanks for reply 😄

**Pull request merged**
