### PR TITLE
fix(rangeInput): fix a bug that floating number cannot be typed

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Summary

This PR fixes a regression which disabled floating numbers in rangeInput widget.

**Before this PR**
```js
  onInput = name => event => {
    this.setState({
      [name]: Number(event.currentTarget.value),
    });
  };
```

When user wants to type "10.34", that callback will be fired with the following `event.currentTarget.value` values:

- `1`
- `10`
- `10.`
- `10.3`
- `10.34`

When it had "10.", `Number("10.")` returns `10` which makes the input value back to `10`. So people never can get to "10.3".

So I removed `Number()` function there (which was the case before the regression). And I used `Number()` when refining.

* [The working example from this branch](https://codesandbox.io/s/instantsearchjs-0d34s?file=/src/app.js:382-470)
* [The failing example from master(v4.5.0)](https://codesandbox.io/s/instantsearchjs-zg1ri?file=/src/app.js)

**Result**

User should be able to type floating numbers.

### CODE REVIEW

**Comment by francoischalifour** [comment]
Nice! It would be valuable to add a test for this to avoid future regressions. You can draw inspiration from the [`SearchBox` events tests](https://github.com/algolia/instantsearch.js/blob/8195d6e92f20292229d46973b06ee55fe5bdea5d/src/components/SearchBox/__tests__/SearchBox-test.js#L186).

**Comment by eunjae-lee** [comment]
@francoischalifour Yesterday I tried to add a test for that, but it was hard to simulate user input like in real world.
In real world, we type and it adds each character at a time to input, but with testing-library, it just triggered an event with a value like '10.34'.

Today I tried their [user-event](https://testing-library.com/docs/ecosystem-user-event) package which is supposed to give a better simulation.
I ran

```js
await userEvent.type(minInput, '10.34');
```

but it triggered the following 5 events.

- 1
- 10
- 10.
- 10.3
- 10.34

So this obviously cannot cover this regression. I think it could be only possible with real e2e test like selenium or cypress.

**Comment by francoischalifour** [comment]
Is it not possible to tell the testing library to type `10.` and to expect that the input is effectively `10.`, and not `0`?

**Comment by eunjae-lee** [comment]
It turns out it's not that easy 😅
https://github.com/testing-library/react-testing-library/issues/678

**Comment by francoischalifour** [comment]
Right, let's merge this as-is then.

**Pull request merged**
