### PR TITLE
doc(getting-started): Some links are unclickable

### PR DESCRIPTION
**Pull request by mikaa123**
**What project are you opening a pull request for?**
- react-instantsearch docs

**Summary**
In the docs, [links that are followed by an `h2`](https://community.algolia.com/instantsearch.js/react/Getting_started.html#load-the-theme) are not clickable:

clicking-issue

This prevents the user from accessing them.
This is due to the `h2:before` overflowing the underlying text.

**Result**

After removing `h2:before`, the block doesn't overflow the text anymore:
slice

### CODE REVIEW

**Comment by bobylito** [comment]
Hi @mikaa123 thanks for the contribution. I will review that asap :)

**Comment by vvo** [comment]
@mikaa123 Tricky, that code is actually here so that when you use the anchors they are not hidden behind the header, if you try to click an anchor on your update it should fail because it will be hidden behind the fixed header bar.

@LukyVj can you give help maybe?

**Comment by mikaa123** [comment]
@vvo thanks for the feedback, you're completely right!

I used `pointer-events` instead. It won't work in IE < 11, if that's an issue.

**Comment by vvo** [comment]
Ok let's merge this and see if it works

**Comment by LukyVj** [comment]
My bad, didn't saw the notification. Let me know if it works

**Comment by vvo** [comment]
Weirdly @mikaa123 this is not sufficient because now every h2 title cannot bo hovered to get the anchor showing (compare with h3 titles). Can we fix that?

**Pull request merged**
