### PR TITLE
chore(release): automatically update website, search index, cdn cache

### PR DESCRIPTION
**Pull request by vvo**
We will now automatically update the website at the right time: when
the release is available on jsdelivr.

We will also update the search index when gh-pages is built.

Also added npm run view-changelog to see the changelog since last stable release

### CODE REVIEW

**Comment by pixelastic** [comment]
Whoo this looks really nice. Could be nice to have a (visual?) explanation of the workflow (what happens asynchronously and where when we push something)

**Comment by vvo** [comment]
Yes so once we merge on master we do:
- run the tests
- wait for the release to be available on jsdelivr (automatically)
- clear the cdn cache
- regenerate the docs website (jsdocs were already generated on npm run release)
- push to gh-pages the updated website
- regenerate the jekyll search index

So the new release process is .. npm run release on master

**Comment by pixelastic** [comment]
Yep, I got the gist of the process, my questions were more:

- Who run the tests? Is that locally on the machine doing the push or on Travis?
- How do you wait for the release to be available? Do you get a pingback or do you need to poll? Also, how long does it usually take?

After that I guess this is a dance between GitHub and Travis. Travis builds the new website, pushes it to `gh-pages`, wich triggers a new Travis build that will update the search index?

**Comment by vvo** [comment]
release is launched by a maintainer (npm run release on master).

once pushed to master, travis do the hard job (and run the test again for safety).

> How do you wait for the release to be available?

https://github.com/algolia/instantsearch.js/blob/master/scripts/finish-release.sh#L12-L24

> Also, how long does it usually take?

Between one and 30 minutes, depends on the jsdelivr bot (also is it's just a website update, not a new release, then it's immediate).

we do not use the gh-pages build on travis because travis won't launch any build of gh-pages.

So on master, we just push to gh pages and then right away update the search index

**Comment by pixelastic** [comment]
> https://github.com/algolia/instantsearch.js/blob/master/scripts/finish-release.sh#L12-L24

And Travis accepts a 30mn timeout? Nice.

**Comment by vvo** [comment]
Yes timeout is like 50+ minutes

**Pull request merged**
