### PR TITLE
docs(storybook): add default style + add storybook to docs build

### PR DESCRIPTION
**Pull request by mthuret**
storybook

### CODE REVIEW

**Comment by bobylito** [comment]
The changes are mostly about deleting some content, is it normal?

**Comment by mthuret** [comment]
Nop. It's me forgetting to commit stuff.

It should be ok now

**Comment by vvo** [comment]
How does this integrates with the dev environement right now? I guess it does not, maybe I can help you here. let me know

**Comment by mthuret** [comment]
@vvo What do you mean with "integrates with the dev". Launching storybook with npm start ? 
Currently it does not. If you want to use it, you need to do "npm run storybook".
What's your expectation ?

**Comment by vvo** [comment]
> What's your expectation ?

If I understood well, we are gonna show examples that are iframes linking to /storybook examples? If so, at some point (maybe not now?) we will need to tackle that.

Is that correct?

**Comment by mthuret** [comment]
Include storybook examples within the doc will be done with #1339 👍

**Pull request merged**
