### PR TITLE
fix(SearchBox): add missing translations

### LINKED ISSUE #1952: SearchBox dom breaking change in 2.2.0 and later
**Do you want to request a *feature* or report a *bug*?**

Bug.

**Bug: What is the current behavior?**

In `2.2.0` and later, the SearchBox widget ignores translation strings, shows large icons, and breaks previous rendering as shown below without a major version change, which means packages are automatically upgraded by NPM according to semantic versioning.

This backwards-incompatible breaking change is undocumented.

screen shot 2017-02-06 at 2 42 13 pm

**Bug: What is the expected behavior?**

In `2.1.0` the SearchBox widget rendered as below, respecting the translation strings [as documented](https://community.algolia.com/instantsearch.js/react/widgets/SearchBox.html). Some of the CSS here (borders, font size) is our theme, but the base is the SearchBox widget's.

screen shot 2017-02-06 at 2 50 56 pm

**Bug: What browsers are impacted? Which versions?**

All.

**What project are you opening an issue for?**
- react-instantsearch

**What is the version you are using? Always use the latest one before opening a bug issue.**

We are forced to pin our version to `<2.2.0` (meaning: `2.1.0`) until we find some way to restore the old rendering behavior. An automatic upgrade according to semantic versioning of the default `^2.1.0` version string put us on `2.2.5`. We were able to narrow it down to the `2.2.0` release as introducing this new breaking behavior, most likely PR #1795.

Here is a snippet of our code that generated the previous rendering on `2.1.0` and the broken rendering on `2.2.0` and later:

```jsx
// components/InstantSearch.js
            <div className="InstantSearch">
                <InstantSearch
                  appId={app_id}
                  apiKey={key}
                  indexName={index}
                  searchState={this.state.searchState}
                  onSearchStateChange={this._onSearchStateChange}
                  searchParameters={{hitsPerPage: 50}}>
                  <SearchBox
                      autoFocus={true}
                      translations={{
                          submit: "Search",
                          reset: "Reset",
                          placeholder: "Search for users ...",
                      }} />
                  <Stats />
                  <Hits hitComponent={UserSummary} />
                </InstantSearch>
            </div>

```

```css
/* components/InstantSearch.css */
.ais-SearchBox__input {
    border: 2px solid grey;
    border-radius: 5px;
    font-size: 24px;
    padding-top: 8px;
    padding-bottom: 8px;
    padding-left: 16px;
    padding-right: 16px;
    width: 350px;
}

/* Hide the blue focus outline */
.ais-SearchBox__input:focus {
    outline: 0;
}

.ais-SearchBox__reset {
    background-color: white;
    border-radius: 5px;
    border: 2px solid lightgrey;
    color: grey;
    font-size: 24px;
    height: 48px;
    margin: 12px;
    padding-bottom: 8px;
    padding-left: 16px;
    padding-right: 16px;
    padding-top: 8px;
}

.ais-SearchBox__reset:focus, .ais-SearchBox__reset:active {
    outline: 0;
    background-color: #fdd;
}
```

### PR DESCRIPTION
**Pull request by mthuret**
fix #1952

### CODE REVIEW

**Comment by vvo** [comment]
Does it still make sense to have translations on the SearchBox since it's icon based?

See 
image

https://deploy-preview-1954--algolia-instantsearch.netlify.com/instantsearch.js/react/storybook/?knob-translate=%7B%22submit%22%3A%22submit%22%2C%22reset%22%3A%22test%22%2C%22submitTitle%22%3A%22Submit%20your%20search%20query.%22%2C%22resetTitle%22%3A%22Clear%20your%20search%20query.%22%2C%22placeholder%22%3A%22Search%20your%20website.%22%7D&selectedKind=SearchBox&selectedStory=playground&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs

**Comment by mthuret** [comment]
I think we should keep it as some people are already using it in a "button first" way. 

I didn't remember that the playground was using values for those buttons. Maybe we could just remove them by default?

**Comment by vvo** [comment]
@shakefu, going further we would like to propose you to have:

```jsx
<SearchBox
  resetComponent={() => 'reset'}
  submitComponent={() => 'Submit'}
/>
```

Since we switched to an icon based default searchbox, providing translations for reset and submit is no more relevant, we are not translating anything here, just hacking around.

That's why we think letting you provide your own reset and submit components is maybe the best idea, so you could even configure icons.

Another solution for you would be to switch to [connectSearchBox](https://community.algolia.com/instantsearch.js/react/connectors/connectSearchBox.html) since you are willing to change the complete design of it now.

What do you think?

**Comment by vvo** [comment]
Closing since we will probably do something different given @shakefu answer

**Comment by vvo** [comment]
cc @shakefu interested in the proposal? Anyone else interested chime in so we know it's something you would like.

Also maybe @Haroenv since you tried to style the actual searchbox lately

**Comment by Haroenv** [comment]
Would that make more sense if the *component were a react element (like: 

```jsx
<SearchBox
  resetComponent={() => <Cross />}
  submitComponent={() => <span>search</span>}
/>
```

Or is that actually the same?

**Comment by shakefu** [comment]
@vvo @Haroenv Either solution (translation string in prop or JSX element in prop) would work really well!

**Comment by vvo** [comment]
> Or is that actually the same?

I was not precise enough, this is what I want to provide. @Haroenv wanna have a try at a first code contribution to react-instantsearch? Go for it!

**Pull request closed without merging**
