### PR TITLE
fix(utils): circular dependency in createSendEventForHits

### PR DESCRIPTION
**Pull request by shortcuts**
**Summary**

Fix circular dependency in createSendEventForHits

```
src/lib/utils/index.ts -> src/lib/utils/createSendEventForHits.ts -> src/lib/utils/index.ts
```

### CODE REVIEW

**Review by Haroenv — APPROVED** [review]
indeed the only one left. Do you think we could add a test for this?

**Comment by Haroenv** [comment]
(careful when merging that the commit message is correct)

**Comment by shortcuts** [comment]
> indeed the only one left. Do you think we could add a test for this?

@Haroenv As our build warns us, couldn't we make it throw if there's one?

**Comment by Haroenv** [comment]
We could use `onwarn` to throw certain warnings as errors? https://rollupjs.org/guide/en/#onwarn

**Comment by shortcuts** [comment]
> We could use `onwarn` to throw certain warnings as errors? https://rollupjs.org/guide/en/#onwarn

Done in https://github.com/algolia/instantsearch.js/pull/4682

**Pull request merged**
