### PR TITLE
fix(hitsPerPageSelector): Issue when state did not have a `hitsPerPage`

### PR DESCRIPTION
**Pull request by ElPicador**

### CODE REVIEW

**Comment by vvo** [comment]
WFM, widgets should not be dependent from other widget instantiation

**Comment by Jerskouille** [comment]
@vvo 2fast2merge

We just talked with @ElPicador and here is the breakdown:

The hits widget has a default value on `hitsPerPage`, so it should almost never be `undefined`, and if it is, I'm fine with forcing the user to set it in `options.searchParameters` at initialization time to be one of these values.

I'm seeing one issue with it though, if there was a specific `hitsPerPage` at some point that was shared in a link and the dev overrides the available options. To solve this, I think it might make sense to do a warning instead of an error, but not silently accepting `undefined`.

**Comment by vvo** [comment]
> The hits widget has a default value on hitsPerPage, so it should almost never be undefined, and if it is, I'm fine with forcing the user to set it in options.searchParameters at initialization time to be one of these values.

It is undefined if you have not instantiated a hits widget OR if you have your own way to display the hits (custom widget). Then state.hitsPerPage is not mandatory, you may just want to use the one from the index/key etc..?

**Comment by Jerskouille** [comment]
For me we shouldn't silently let it go, you never want to have no selected value on a hits per page selector.

And this PR works for undefined, but not for any number that isn't in the options.

**Comment by vvo** [comment]
> And this PR works for undefined, but not for any number that isn't in the options.

I do not understand the issue for this one, can you give an example?

**Comment by vvo** [comment]
I fail at seeing every cases/issues here so if you have another proposition @Jerskouille go for it.

**Comment by vvo** [comment]
Thanks to @Jerskouille we found more issues linked to this one, will do some more changes

**Pull request merged**
