### PR TITLE
chore(dev): automatically deploy instantsearch.js v1 website on PRs

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
Works, we now have both react-instantsearch and instantsearch.js websites deployed on every PR, should make it easier to iterate soon on instantsearch.js website.

**Comment by vvo** [comment]
Example: https://deploy-preview-1983--algolia-instantsearch.netlify.com/

**Comment by Haroenv** [comment]
That's great

**Comment by vvo** [comment]
The live examples are also using the build of instantsearch.js that comes from the branch. So everything being shown on the website is really the branch work, not reusing any production asset. (isolation)

**Comment by bobylito** [comment]
Noice!! :D

**Pull request merged**
