### PR TITLE
Upgrade preact-compat

### PR DESCRIPTION
**Pull request by bronzehedwick**
**Summary**

Updrading preact-compat fixes IE 11 + Google Maps clashing. My previous commit (see below) did not address the issue in the preact-compat library, which is also effecting. Upgrading the library resolves this.

**Result**

- https://github.com/algolia/instantsearch.js/pull/2749
- https://github.com/developit/preact-compat/pull/423

### CODE REVIEW

**Comment by bronzehedwick** [comment]
Folks responding to https://github.com/algolia/instantsearch.js/pull/2749 were correct: I was confused about where the error was actually coming from. While the Symbol checks in instantsearch *might* have also caused a problem, the real issue was the checks in preact-compat, which the mentioned PR resolves.

My apologies for my wrongness.

**Comment by bobylito** [comment]
Hi @bronzehedwick thanks for opening this PR and for taking the time to contribute. However we can't upgrade to this version because it breaks the slider (https://deploy-preview-2751--algolia-instantsearch.netlify.com/v2/dev-novel/?selectedStory=RangeSlider.default) I haven't had time to investigate this specific issue even though encountered it when trying to upgrade the preact-compat lib too.

**Comment by bronzehedwick** [comment]
Ah ok, that's a bummer. I think we're going to go ahead with a fork for now, since we're not using the slider and we'd like to release this coming Tuesday. We can switch back to reference the upstream code once the issues have been worked through.

Thanks so much for your help!

**Comment by bobylito** [comment]
Sorry about that @bronzehedwick Going with your own fork might be the best for now indeed

**Pull request closed without merging**
