### PR TITLE
ci(test-strategy): Split travis tasks

### PR DESCRIPTION
**Pull request by bobylito**
The goal of this PR is give us a better visibility of what failed during the CI tests.

To achieve this goal, the script has been split and some dead code was removed.

### CODE REVIEW

**Comment by bobylito** [comment]
Meh no real benefits :(

**Comment by Haroenv** [comment]
try the build matrix, that will show up as two travis checks :) --> https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

**Comment by bobylito** [comment]
You're right and you already told me :( I found this one that goes into more depth https://docs.travis-ci.com/user/speeding-up-the-build/

**Comment by Haroenv** [comment]
:( this doesn't give multiple checks

by the way, the commit message check doesn't need to run yarn and can be shorter: https://travis-ci.org/algolia/instantsearch.js/jobs/362045579#L590

**Comment by bobylito** [comment]
> :( this doesn't give multiple checks

:(



> by the way, the commit message check doesn't need to run yarn and can be shorter: https://travis-ci.org/algolia/instantsearch.js/jobs/362045579#L590

Ok :)

I think overall that's an improvement:

screen shot 2018-04-04 at 11 52 46

I'd be in favor in splitting down the tasks even further: unit / functional / lint. What do you think @Haroenv ?

**Comment by Haroenv** [comment]
https://github.com/travis-ci/travis-ci/issues/5035 && https://github.com/wizeline/travieso are the reason it isn't split in multiple checks. It's probably not worth the effort to have multiple separate checks

**Comment by Haroenv** [comment]
interesting behaviour here, the split test takes almost the same amount of time as the non-split one 😢

**Comment by bobylito** [comment]
I couldn't find any way not to install yarn.

Even though the time is not decreasing, this PR provides 2 benefits:
 - better view of what's problematic
 - ability to restart part of the CI checks (looking at you functional tests)

Merge?

**Comment by Haroenv** [comment]
merge!

**Pull request merged**
