### PR TITLE
fix(pagination): reset on other filter + no toggle

### PR DESCRIPTION
**Pull request by bobylito**
The bug is caused by the use of two conflicting semantics
with the same set of changes. Previously we had "if the value for the
page, reset the page number", which led to reseting the pager to 0
if we were selecting the same page (the toggle effect). I previously
removed this behaviour, but it introduced the impossibility to reset
the pager to 0 when changing any other filter (setting the value was
the trigger).

In order to fix this issue I introduce a new type of value to
express the intent of using the same value without changing the page.
This way we have two distinctly defined intents and values:
 - same value as numbers -> reset to 0
 - value with isSamePage flag -> change to page value

It relies on `valuesOf`, which is not that nice and introduces the use
of the dreaded `==`. At least, I can say that I found a legit use case
for it. Bottom line, I'm open to suggestion here :)

### CODE REVIEW

**Comment by Morhaus** [comment]
Another way to do this would be to have [`Pagination.connect.refine`](https://github.com/algolia/instantsearch.js/blob/v2/packages/react-instantsearch/src/widgets/Pagination/connect.js#L41) be the identity function when the page hasn't changed.

Then have [`Pagination.connect.transitionState`](https://github.com/algolia/instantsearch.js/blob/v2/packages/react-instantsearch/src/widgets/Pagination/connect.js#L51) also be the identity function in the case where `prevState === nextState`.

**Comment by bobylito** [comment]
@Morhaus I will try that, that's obviously less convoluted :)

**Comment by bobylito** [comment]
> Then have Pagination.connect.transitionState also return prevState unchanged in the case where prevState === nextState.

Humm but then when do we reset the page?

**Comment by Morhaus** [comment]
When `prevState[id] === nextState[id]` and `prevState !== nextState`.

This might mean that we need to have other widget's refine method return the same state object when it would previously yield an equivalent state.

**Comment by bobylito** [comment]
> When prevState[id] === nextState[id] and prevState !== nextState.

Ok I see, that's indeed some big change all around the code base :)

**Comment by Morhaus** [comment]
Yep, but I think it makes sense.

We could also replace the triple equality check with a deep comparison, which would remain cheap provided we don't have too many complicated states. That shouldn't be a problem with the widgets we have right now.

**Comment by vvo** [comment]
reading the PR and the previous implementation I wonder if we are going the right direction.

Basically the need is to reset page to 0 on most refines. So why would the pagination widget be responsible for that? This circles back to how the helper does it to me.

What if the various widgets were made responsible for the page to show and not the pagination connector itself.

Wouldn't it make things obvious and remove the need for "transitionState" API (which only exists because of that page: 0 need). Not very DRY but explicit and simple, before we find a good API to express that (if there's the need, I am not sure).

**Comment by Morhaus** [comment]
So would every widget reset the page state on refine?

This is something I wanted to avoid, because it makes changing the pagination state key difficult.

**Comment by bobylito** [comment]
Or it could be handled by the core like in instantsearch.js / helper.

For now, I would rather have something that does the job (this PR) without having to rewrite the core or go against the current principles of the library. We could rethink that later.

**Comment by vvo** [comment]
> So would every widget reset the page state on refine?

Yes

**Comment by vvo** [comment]
> For now, I would rather have something that does the job (this PR) without having to rewrite the core or go against the current principles of the library. We could rethink that later.

WFM

**Pull request merged**
