### PR TITLE
Prevent slider from extending farther than the last pip

### LINKED ISSUE #708: Range Slider last pip not aligned to the right of the slider
Issue opened on the wrong repository (instantsearch/instantsearch-ion.rangeSlider#1)
Browser is Chrome 46.0.2490.86 (64-bit)

I'll push a PR to fix according to the discussion we've had there

---
I'm not sure whether this is due to the default styling or to the column the slider is contained in...
No external styles seem to be applied to the widget.

Here 5000$ is the maximum value but the slider goes a few pixels out to the right:

capture d ecran 2015-11-30 18 07 07

By commenting `width: 100%` in the `.ais-range-slider--base` rules, I get a correct display:

capture d ecran 2015-11-30 18 10 34

In none of both cases does the slider actually take up 100% of its container...

### PR DESCRIPTION
**Pull request by olance**
Fix #708

### CODE REVIEW

**Comment by redox** [comment]
@olance we have a strict [contributing policy](https://github.com/algolia/instantsearch.js/blob/master/CONTRIBUTING.md#commit-message-guidelines). Here the tests are failing because your commit message doesn't follow the "Angular.js conventional changelog" pattern.

It should be `fix(rangeSlider): 	prevent slider from extending farther than the last pip`.

**Comment by olance** [comment]
@redox that should be OK now? :)

**Comment by redox** [comment]
:+1: @olance

**Comment by pixelastic** [comment]
@redox: Do you think the message you wrote could be added as some part of automatic check by the algobot?

**Comment by redox** [comment]
Yes, need to check how to do that; but definitely :)

**Comment by vvo** [comment]
Basically we could just develop our own algolia contribution bot doing more checks but right now travis already does a decent job

**Comment by pixelastic** [comment]
Maybe just posting the Travis error message (if we can get the meaningful one in the list) in the thread.

**Pull request merged**
