### PR TITLE
feat(es7): Enable `es7.objectRestSpread`

### PR DESCRIPTION
**Pull request by pixelastic**
This will enable us writing this like:

```js
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };
```

or

```js
var defaults = { first: 'John', last: 'Doe', age: 42 };
var trainer  = { last: 'Smith', age: 35 };
trainer      = { ...defaults, ...trainer, age: 36 }
// => { first: 'John', last: 'Smith', age: 36 }
```

More info: https://github.com/sebmarkbage/ecmascript-rest-spread

Babeljs should have this enabled by default, but it seems than for it
to work when using the babel plugin for webpack, we need to explicitly
enable it.

### CODE REVIEW

**Comment by vvo** [comment]
About the issue: https://github.com/babel/babel-loader/issues/117

**Comment by pixelastic** [comment]
I blindly copy-pasted the solution suggested in an issue in `babel-loader` at first. Then I tried with `stage: 2` and this failed. Now I'm having `segfaults` on `npm run dev` :/

**Comment by vvo** [comment]
segfault is really weird

**Comment by pixelastic** [comment]
I deleted my `node_modules` and re-`npm install`-ed it and it is working fine. I think webpack might not like live-editing of `.babelrc`.

I've re-pushed with `stage:2`

**Comment by vvo** [comment]
> I deleted my node_modules and re-npm install-ed it and it is working fine. I think webpack might not like live-editing of .babelrc.

If you just upgrade node then you need to rm -rf node_modules indeed. Because some of the modules have native code compilation. Thus it can fail when upgrading major node.

**Comment by pixelastic** [comment]
Oh ok, makes sense. Thanks for the trick.

**Pull request merged**
