### PR TITLE
fix(poweredBy): fixed Algolia logo version

### LINKED ISSUE #1222: Better PoweredBy logo
The current powered by logo is not very nice: it is blurred, not retina ready and doesn't scale well.

image

### PR DESCRIPTION
**Pull request by redox**
This blue-ish one is the very latest version.

algolia-light- 1

Fix #1222

### CODE REVIEW

**Comment by vvo** [comment]
Does It Scales?:tm:

**Comment by bobylito** [comment]
And it is smaller! :D

**Comment by redox** [comment]
> Does It Scales?™️

The image is twice the size specified in the CSS: it's the basic/simple way to support retina screen.

**Comment by vvo** [comment]
I am ok updating the logo to the latest design, just worried that we need to maybe go a bit further to really solve #1222 in case it's still blurry (that's the initial request)

**Comment by redox** [comment]
Updated to use the SVG version, bye bye IE < 9.

**Comment by rayrutjes** [comment]
Looks so much better:
image

**Comment by vvo** [comment]
That's ok for IE8, we do not support it.

**Pull request merged**
