### PR TITLE
chore(doc): make link relative in customization guide

### PR DESCRIPTION
**Pull request by bobylito**

### CODE REVIEW

**Comment by gzzo** [comment]
Has this been deployed?  This link is 404 on https://community.algolia.com/instantsearch.js/v2/guides/customization.html

**Comment by vvo** [comment]
It's good now

**Comment by gzzo** [comment]
@vvo On the latest version of Chrome (64.0.3282.186), this link is still 404.   It looks like /guides isn't treated as a folder for some reason, since changing the `href` to `"connectors.html"` links to the proper document.

**Comment by vvo** [comment]
@gzzo which link is 404 on your end?

**Comment by gzzo** [comment]
@vvo 


> Now you can **read more about connectors** in the docs and create more advanced usages with the same simplicity.


Links to https://community.algolia.com/instantsearch.js/connectors.html (404)

**Comment by vvo** [comment]
Fixed by @Haroenv I believe, thanks for feedback

**Pull request merged**
