### PR TITLE
Chore(utils) : adds tests for utils module

### PR DESCRIPTION
**Pull request by bobylito**
Also added doc and did some refactoring. (not rebased but I'd like the feedback before)

### CODE REVIEW

**Comment by bobylito** [comment]
Test framework was updated after I started this branch. Not cool :( Going to sleep...

**Comment by bobylito** [comment]
Found mocha-jsdom, cool

**Comment by vvo** [comment]
> Found mocha-jsdom, cool

Yep you only need to call jsdom() and import it (see other test doing so).

So you can sleep well man :)

**Comment by bobylito** [comment]
BOOOOOM!

**Comment by vvo** [comment]
LGTM

**Pull request merged**
