### PR TITLE
fix(selector): makes component as uncontrolled component

### LINKED ISSUE #365: Issue with Selector rendering
On Firefox 41.0.2, I get this weird issue on a value selection where it displays: 
- The selected option
- The first option for a fraction of a sec
- The selected option back again

selector bug

It seems like `render` is only called once, but I believe the issue might be caused by the replacement of the select in the DOM.

### PR DESCRIPTION
**Pull request by redox**
Fix #365

### CODE REVIEW

**Comment by bobylito** [comment]
This introduces a bug! If you press the back button, the value of the select won't be updated anymore.

**Comment by Jerskouille** [comment]
@bobylito Can you tell us what is the difference between a controlled and uncontrolled component? I couldn't understand it from the docs.

**Comment by vvo** [comment]
So do we do something to solve what @bobylito said here?

**Comment by pixelastic** [comment]
We should open a new issue for tracking this bug, with a simple repro case (I did not get if it was pressing backspace in the input, or in the webpage -to go to previous page- that triggered the issue).

cc @bobylito

**Pull request merged**
