### PR TITLE
perf(filesize): use preact in production build

### PR DESCRIPTION
**Pull request by vvo**
instantsearch.min.js **React build** => 113kb (gzipped)
instantsearch.min.js **preact build** => 77kb (gzipped)

### CODE REVIEW

**Comment by bobylito** [comment]
Love that! Is it possible to offer two builds?

**Comment by vvo** [comment]
> Love that! Is it possible to offer two builds?

Yes feasible, but how would we guide users towards them? As a user of instantsearch.js I am not aware of either React or preact so not sure how I could make a choice.

But it's a good idea to be able start testing this build yes. We could also just push it and see what happens. Our heavy demo is working with it so if we have glitches they should not happen on that many websites.

**Comment by redox** [comment]
That's awesome 👍

**Comment by bobylito** [comment]
> Yes feasible, but how would we guide users towards them? As a user of instantsearch.js I am not aware of either React or preact so not sure how I could make a choice.

True, mainly wondering on the possibility... Would you like to test that in the wild?

**Comment by vvo** [comment]
> Would you like to test that in the wild?

Will test it with magento and wordpress extensions, if it works then :shipit:

**Comment by vvo** [comment]
:white_check_mark: tested in magento
:white_check_mark: tested in wordpress

**Comment by vvo** [comment]
- [ ] investigate functional tests
- [ ] test on mobile

**Comment by developit** [comment]
😍

**Comment by vvo** [comment]
Tests are :white_check_mark:, let's release this

**Comment by vvo** [comment]
Since we were exposing that we accepted React components as templates and it was accessible in the production build, I had to rollback the default build and create a specific preact build. This should not be an issue in ISV2 where we will completely hide the fact that we use react/preact for non react users.

**Comment by developit** [comment]
@vvo Good catch, sorry I didn't have the context to spot that before hand

**Comment by vvo** [comment]
@developit its entirely our responsibility no worriess ahah. In V2 this need will disappear and we will use preact by default

**Comment by developit** [comment]
Are you guys switching to allowing templates instead, or something else? (just curious!)

**Pull request merged**
