### PR TITLE
docs(animation): Add anti-aliasing for Firefox

### PR DESCRIPTION
**Pull request by Jerskouille**
Before:
aliased

After:
anti-aliased

### CODE REVIEW

**Comment by redox** [comment]
Oh didn't know that trick :) Interesting!

**Comment by Jerskouille** [comment]
Credit where it's due, comes from http://stackoverflow.com/a/27065674 .

**Comment by vvo** [comment]
Can you link the stackoverflow topic in the comment, for reference

**Comment by Jerskouille** [comment]
? In the commit message? How is it different from linking it here? I thought you guys weren't using `git log` ?

**Comment by vvo** [comment]
No no in the code itself

**Comment by Jerskouille** [comment]
Oh, OK.

**Comment by Jerskouille** [comment]
Done

**Pull request merged**
