### PR TITLE
chore(doc): display some debug info when inspecting the HTML of a widget

### LINKED ISSUE #403: Documentation: show the default css classes on top of the rendered widget
@alexandremeunier had a good idea: actually show the rendered css classes names in the widget demo documentation. Maybe there are some already existing libs to do so.

### PR DESCRIPTION
**Pull request by redox**
Fix #403

### CODE REVIEW

**Comment by vvo** [comment]
That's awesome, does it only toggle this mode when you click on "view html"? Or is it always activated

**Comment by redox** [comment]
> That's awesome, does it only toggle this mode when you click on "view html"? Or is it always activated

Yes, only when you toggle -> I think it was more convenient.

**Comment by vvo** [comment]
Yes it's more convenient but I wonder if that's easy to understand. Actually I think that's not easy to understand at all because you trigger a tab on the right and it triggers a behavior also on the left so you could discover this by trying only (= luck).

What about a checkbox/button on the right of "widget display" in your screenshot that says "view underlying css classes" or "toggle css debug" "view class names"?

**Comment by redox** [comment]
Yes good point, not yet sure where to put it to look nice.

**Comment by redox** [comment]
OK, I've another proposal: always highlight the first level once the `View HTML` button is clicked, I think it's the best of the 2 worlds:

**Comment by vvo** [comment]
Yes should be sufficient, if at some point it still not obvious we will think again

**Pull request merged**
