### PR TITLE
Fix/967

### PR DESCRIPTION
**Pull request by redox**

### CODE REVIEW

**Comment by vvo** [comment]
This fails when building from production: asset digests are no more generated. Arg

**Comment by vvo** [comment]
Only je jekyll-assets functions (js, css, asset_path) will generate digests

**Comment by redox** [comment]
> Only je jekyll-assets functions (js, css, asset_path) will generate digests

Arg...

**Comment by vvo** [comment]
The whole jekyll + livereload + jekyll assets field is a complete mess. Not because of our requirements/usage, it's just a mess solved by either doing code (gulp, grunt) or using extensions that are failing like we see right now.

I suggest we move to middleman very soon because I already spent one hour trying to figure out what's not working.

**Comment by redox** [comment]
@vvo I finally made it work downgrading to jekyll 2.5 (livereload OK, update CSS/JS triggers rebuild, asset digests in production).

**Pull request closed without merging**
