### PR TITLE
fix(menuSelect): select in userCssClasses

### PR DESCRIPTION
**Pull request by remarks**
**Summary**

Bug fix: `select` in `cssClasses` are currently applied to `footer` element.

### CODE REVIEW

**Comment by Haroenv** [comment]
Could you run `yarn test -u` to update the snapshots? see https://travis-ci.org/algolia/instantsearch.js/builds/283887455#L1023

**Comment by bobylito** [comment]
Thanks @remarks ❤️

**Comment by iam4x** [comment]
Nice catch, thanks @remarks 👍

**Comment by remarks** [comment]
Thanks all! Sorry about testing, will remember that next time. This was my first useful OSS contribution I've done so just wanted to get it out there.

**Comment by Haroenv** [comment]
that's even cooler @remarks 😄

**Comment by bobylito** [comment]
> Thanks all! Sorry about testing, will remember that next time. This was my first useful OSS contribution I've done so just wanted to get it out there.
>  🎉 1

We're very grateful that your first contribution was on our project 🙇 You'll always be welcome to contribute here. Let us know if you'd like to tackle other subjects but you don't know how to start.

**Pull request merged**
