### PR TITLE
fix(toggle) make autoHide check facetValue.count

### PR DESCRIPTION
**Pull request by rogerroelofs**
Activating a toggle with 0 hits puts the user in a state where they can't get back to the previous state.  The toggle and many other widgets autoHide when no results are found.  This change will autoHide the toggle if changing it's state would result in 0 hits.

Issue #1185

### CODE REVIEW

**Comment by rogerroelofs** [comment]
In the case where the off state doesn't have a value (i.e. means don't use the attribute in the search) the count should be the number of hits for 'don't use' rather than the number of hits for 'false'   I'd like someone from the project to validate that before I go changing the tests to match my assumption.

**Comment by vvo** [comment]
Hi @rogerroelofs, thanks for reporting this issue and for the associated PR! Here are my comments:

> This change will autoHide the toggle if changing it's state would result in 0 hits.

This would be in-line with what is done today for other widgets indeed. But we could maybe also do something a bit different: what if as soon as we know toggling would result in no hits we show the toggle as disabled? As for the default rendering it would mean adding `disabled` to the toggle checkbox.

Then we would be able to still allow the user to untoggle if the current state is 0 hits and untoggling would mean showing some hits.

What do you think?

> In the case where the off state doesn't have a value (i.e. means don't use the attribute in the search) the count should be the number of hits for 'don't use' rather than the number of hits for 'false'

That's right and this we can change it.

I am blow away by the fact that you understood so much from our codebase and were able to hack in the toggle code which is not that easy to understand (read: complex, not smart :p).

If you are down to continue this PR based on my first comment then go for it, add tests if you feel like it otherwise we will do it.

Thanks a lot

**Comment by timkelty** [comment]
@vvo @rogerroelofs I'm actually working with @rogerroelofs on this issue.

As the PR stands, this is exactly how I want it to behave in my case. I see the value of the `disabled` suggestion, but feel like that should be a different option (`autoHideContainer` is pretty explicit).

Could be `disableOnEmpty` or something.

**Comment by vvo** [comment]
@timkelty Ok this works for me, in the next instantsearch.js iteration we might default to the disabled solution.

**Comment by vvo** [comment]
I will update the tests, thanks

**Comment by timkelty** [comment]
@vvo Yep, I think defaulting to disabled would be good (since you never want to toggle to see nothing). Then the container hiding feature can still be controlled via `autoHideContainer`

**Comment by vvo** [comment]
> Yep, I think defaulting to disabled would be good (since you never want to toggle to see nothing). Then the container hiding feature can still be controlled via autoHideContainer

Exactly

**Comment by vvo** [comment]
Fixed with #1213, sorry I messed up in merging and did not include commits. I will be careful next time.

**Comment by timkelty** [comment]
Great work everyone, hope to see it in a release soon!

**Pull request closed without merging**
