### PR TITLE
fix(CONTRIBUTING): remove section about beta releases

### PR DESCRIPTION
**Pull request by Haroenv**
**Summary**

We don't have beta releases yet (see the [script](https://github.com/algolia/instantsearch.js/blob/develop/scripts/release.sh#L85-L92) and https://github.com/algolia/instantsearch.js/issues/2056), so the contributing section shouldn't be added yet.

We will put this back when `-b` works, and we've found a strategy for making it work with jsDeliver

**Result**

Remove the beta section in CONTRIBUTING for now

### CODE REVIEW

**Comment by bobylito** [comment]
Actually that would be great if we could do a beta release :)

**Comment by Haroenv** [comment]
Yes, but it's not possible for now because of jsDeliver, it will always take the latest release, regardless of git tag...

**Comment by bobylito** [comment]
Would it be possible to beta release in npm only? (I've had the issue you mention before :/) What if we push explicitly to jsDeliver, and do not rely on npm anymore for that?

**Comment by Haroenv** [comment]
I would be okay with not using jsDeliver anymore, and using unpkg like in react-instantsearch

**Pull request merged**
