### PR TITLE
Feat(live-doc): makes documentation works on smaller screens

### LINKED ISSUE #472: Mobile documentation website is currently unusable
I tried to show the instantsearch website at lunch but on mobile it was not unusable.

What can we do for the 1.0.0 release that is not too hard to do but still gives the right experience on mobile?

People WILL access our documentation on mobile, especially at launch when it's all new.

### PR DESCRIPTION
**Pull request by bobylito**
Fixes #472 :)

### CODE REVIEW

**Comment by Shipow** [comment]
@bobylito the select is not super handy with ios

**Comment by pixelastic** [comment]
Mobile menu looks a bit too... spacy :)
2015-11-09_09h57m24

I would not split the content in two columns that early (800px?). On small screens, each column is really narrow. It is more readable to put text and examples one below the other until we really have a a bigger screen (maybe when we start adding the menu column? 1200px?)

image

**Comment by Shipow** [comment]
Mobile menu are made for: mobile, and I think it works well on mobile.

For breakpoints, I'm ok like that but feel free to test.

**Comment by vvo** [comment]
Cool that we are tackling this one.

image

^^^ Is the gif from @pixelastic still accurate? As for the menu (or the whole webpage), it looks really weird that the text is passing below in full transparency.

I know that's a detail but I guess everyone on mobile will stumble on it and their first impression will somehow be different than if it was done in a different manner.

Can we put an opaque background behind "instantsearch.js" so that it's not doing this?

**Comment by vvo** [comment]
need rebase

**Comment by bobylito** [comment]
We have merges because merge :) I think it's not too bad for this time and we'll do better next time :) (we promise)

**Comment by bobylito** [comment]
Can we merge ;D?

**Comment by vvo** [comment]
Yep good @Shipow we can have a git workflow course soon no big deal

**Pull request merged**
