### PR TITLE
refactor(RefinementList): externalize the map iterator

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by bobylito** [comment]
I think we need to move to 0.14 and start making function component.

LGTM

**Comment by vvo** [comment]
> I think we need to move to 0.14 and start making function component.

Yes! #151 is here but maybe we should wait for the complete release?

**Comment by bobylito** [comment]
Yes! Let's finish a big final release and then make a refactoring release :clock1030: (tick tock style)

**Comment by vvo** [comment]
> for the complete release?

I meant for the complete release of 0.14 (currently beta) hehe

**Comment by bobylito** [comment]
Well RC-1 is there, and it should be good enough :)

**Comment by vvo** [comment]
> Well RC-1 is there, and it should be good enough :)

Then we can do it anytime :dancer:

**Pull request merged**
