### PR TITLE
fix(bem): Make scss mixins actually follow BEM

### LINKED ISSUE #507: documentation: rendering of hierarchicalMenu is not correctly indented
Seems like the default theme is not applied, you cannot see that this menu is actually hierarchical.

2015-11-09_10h46m22

### PR DESCRIPTION
**Pull request by pixelastic**
The mixins and internal variable where misnamed. We use the BEM naming
with the following pattern: `.ais-block--element__modifier`.

Mixins where usin `component` instead of `block` and where swapping
`element` and `modifier`. I've reverted to something more readable.

### CODE REVIEW

**Comment by pixelastic** [comment]
Ready for review. This is mostly search and replace of mixins.

**Comment by vvo** [comment]
conflicts

**Comment by redox** [comment]
Thank you @pixelastic, I discovered that a few hours ago as well.

**Comment by redox** [comment]
:+1: @pixelastic

**Comment by pixelastic** [comment]
@redox Why a merge instead of a rebase?

**Comment by redox** [comment]
> @redox Why a merge instead of a rebase?

Arg, I'm used to merge, will do rebase next time. But GitHub does merges as well when you click "Update branch", correct?

**Comment by vvo** [comment]
> But GitHub does merges as well when you click "Update branch", correct?

Yes it does that, it's ok I guess but we are not using the button much (because we do not enforce status check + update for now)

**Comment by pixelastic** [comment]
We rebase feature branches to keep them in sync with `developr during their lifetime, then we merge them into develop (using the GitHub button)

**Comment by vvo** [comment]
> We need to write this down somewhere, do a screencast, an internal crash course or whatever :)

This is the contributing.md right?

**Comment by pixelastic** [comment]
Yes, you might need to expand on it with actuall git commands to run to do all that, for those not yet familiar with git.

**Pull request merged**
