### PR TITLE
chore(doc): foldable sidebar on mobile

### LINKED ISSUE #2221: Sidebar button doesn't open the sidebar on mobile
On mobile, the button to toggle the sidebar documentation doesn't work if clicked.

The sidebar does not toggle.

### PR DESCRIPTION
**Pull request by bobylito**
fix #2221

Also:
 - hide `edit this page` button on mobile

### CODE REVIEW

**Comment by Haroenv** [comment]
I wouldn't hide the button on mobile, I often browse from mobile and don't like it when some stuff is impossible to reach

**Comment by bobylito** [comment]
> I wouldn't hide the button on mobile, I often browse from mobile and don't like it when some stuff is impossible to reach

This is for the edit button. Are you going to edit the page on your phone?

**Comment by Haroenv** [comment]
Yes, I do that 

Sent from my phone

**Comment by bobylito** [comment]
> Yes, I do that

And do you think people will benefit more from the button on mobile? We rarely receive any contribution with it, do you think those are gonna be from mobile?

My point of view is that hiding the button make the UI slightly better (less busy) without removing a contribution opportunity.

**Pull request merged**
