### PR TITLE
docs(searchParameters): Add more explicit example

### PR DESCRIPTION
**Pull request by pixelastic**
**do not merge yet**

I had a question on support about the usage of `searchParameters`.
I updated the doc to make it more explicit.

But I cannot regenerate the doc website from the jsdoc, `npm run docs:jsdoc` fails (see #743)

### CODE REVIEW

**Comment by vvo** [comment]
Most of the time we try to link to https://community.algolia.com/algoliasearch-helper-js/docs/SearchParameters.html, what do you think?

**Comment by pixelastic** [comment]
Oh yes, makes sense. Will update.

**Comment by pixelastic** [comment]
I'm a little afraid of accepting this PR knowing that #743 is not fixed, but we have been having support questions about `searchParameters` that could have been avoided with the proper doc.

Does anyone know why #743 is failing?

**Comment by vvo** [comment]
@pixelastic Can you just comment the {...} from lib/InstantSearch.js, check that the doc is well generated and then we merge this until I fix the jsdoc thing (which is a bug un jsdoc)

**Comment by pixelastic** [comment]
Nice workaround. I've just pushed again with the new generated HTML, but I also have a new `currentRefinedValues.md` added to the log, but not present in the HTML doc. Is this widget officially released?

**Comment by vvo** [comment]
> Is this widget officially released?

Since it's not in the html docs no but I believe the widget is done and can be used. We need to add it thought

**Comment by vvo** [comment]
Ok let's merge this and mode on

**Comment by pixelastic** [comment]
@Jerskouille is working on the "official" release of the currentRefinedValues I think.

**Pull request merged**
